// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"

	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourceJenkins           string = "jenkins"
	ResourceJenkinsSecurity   string = "jenkins.security"
	ResourceJenkinsPlugin     string = "jenkins.plugin"
	ResourceJenkinsJob        string = "jenkins.job"
	ResourceJenkinsNode       string = "jenkins.node"
	ResourceJenkinsCredential string = "jenkins.credential"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"jenkins": {
			// to override args, implement: initJenkins(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJenkins,
		},
		"jenkins.security": {
			Init:   initJenkinsSecurity,
			Create: createJenkinsSecurity,
		},
		"jenkins.plugin": {
			// to override args, implement: initJenkinsPlugin(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJenkinsPlugin,
		},
		"jenkins.job": {
			// to override args, implement: initJenkinsJob(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJenkinsJob,
		},
		"jenkins.node": {
			Init:   initJenkinsNode,
			Create: createJenkinsNode,
		},
		"jenkins.credential": {
			// to override args, implement: initJenkinsCredential(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJenkinsCredential,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"jenkins.url": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkins).GetUrl()).ToDataRes(types.String)
	},
	"jenkins.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkins).GetVersion()).ToDataRes(types.String)
	},
	"jenkins.mode": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkins).GetMode()).ToDataRes(types.String)
	},
	"jenkins.quietingDown": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkins).GetQuietingDown()).ToDataRes(types.Bool)
	},
	"jenkins.plugins": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkins).GetPlugins()).ToDataRes(types.Array(types.Resource("jenkins.plugin")))
	},
	"jenkins.jobs": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkins).GetJobs()).ToDataRes(types.Array(types.Resource("jenkins.job")))
	},
	"jenkins.nodes": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkins).GetNodes()).ToDataRes(types.Array(types.Resource("jenkins.node")))
	},
	"jenkins.credentials": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkins).GetCredentials()).ToDataRes(types.Array(types.Resource("jenkins.credential")))
	},
	"jenkins.security.securityEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsSecurity).GetSecurityEnabled()).ToDataRes(types.Bool)
	},
	"jenkins.security.csrfProtectionEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsSecurity).GetCsrfProtectionEnabled()).ToDataRes(types.Bool)
	},
	"jenkins.security.allowsAnonymousAdmin": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsSecurity).GetAllowsAnonymousAdmin()).ToDataRes(types.Bool)
	},
	"jenkins.security.slaveAgentPort": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsSecurity).GetSlaveAgentPort()).ToDataRes(types.Int)
	},
	"jenkins.plugin.shortName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsPlugin).GetShortName()).ToDataRes(types.String)
	},
	"jenkins.plugin.longName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsPlugin).GetLongName()).ToDataRes(types.String)
	},
	"jenkins.plugin.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsPlugin).GetVersion()).ToDataRes(types.String)
	},
	"jenkins.plugin.enabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsPlugin).GetEnabled()).ToDataRes(types.Bool)
	},
	"jenkins.plugin.active": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsPlugin).GetActive()).ToDataRes(types.Bool)
	},
	"jenkins.plugin.hasUpdate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsPlugin).GetHasUpdate()).ToDataRes(types.Bool)
	},
	"jenkins.plugin.url": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsPlugin).GetUrl()).ToDataRes(types.String)
	},
	"jenkins.plugin.requiredCoreVersion": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsPlugin).GetRequiredCoreVersion()).ToDataRes(types.String)
	},
	"jenkins.job.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetName()).ToDataRes(types.String)
	},
	"jenkins.job.fullName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetFullName()).ToDataRes(types.String)
	},
	"jenkins.job.url": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetUrl()).ToDataRes(types.String)
	},
	"jenkins.job.class": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetClass()).ToDataRes(types.String)
	},
	"jenkins.job.buildable": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetBuildable()).ToDataRes(types.Bool)
	},
	"jenkins.job.disabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetDisabled()).ToDataRes(types.Bool)
	},
	"jenkins.job.lastBuildNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetLastBuildNumber()).ToDataRes(types.Int)
	},
	"jenkins.job.lastSuccessfulBuildNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetLastSuccessfulBuildNumber()).ToDataRes(types.Int)
	},
	"jenkins.job.lastFailedBuildNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetLastFailedBuildNumber()).ToDataRes(types.Int)
	},
	"jenkins.job.description": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetDescription()).ToDataRes(types.String)
	},
	"jenkins.job.node": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsJob).GetNode()).ToDataRes(types.Resource("jenkins.node"))
	},
	"jenkins.node.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsNode).GetName()).ToDataRes(types.String)
	},
	"jenkins.node.description": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsNode).GetDescription()).ToDataRes(types.String)
	},
	"jenkins.node.isController": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsNode).GetIsController()).ToDataRes(types.Bool)
	},
	"jenkins.node.offline": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsNode).GetOffline()).ToDataRes(types.Bool)
	},
	"jenkins.node.temporarilyOffline": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsNode).GetTemporarilyOffline()).ToDataRes(types.Bool)
	},
	"jenkins.node.offlineCauseReason": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsNode).GetOfflineCauseReason()).ToDataRes(types.String)
	},
	"jenkins.node.numExecutors": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsNode).GetNumExecutors()).ToDataRes(types.Int)
	},
	"jenkins.node.labels": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsNode).GetLabels()).ToDataRes(types.Array(types.String))
	},
	"jenkins.credential.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsCredential).GetId()).ToDataRes(types.String)
	},
	"jenkins.credential.typeName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsCredential).GetTypeName()).ToDataRes(types.String)
	},
	"jenkins.credential.description": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsCredential).GetDescription()).ToDataRes(types.String)
	},
	"jenkins.credential.domain": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJenkinsCredential).GetDomain()).ToDataRes(types.String)
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"jenkins.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).__id, ok = v.Value.(string)
		return
	},
	"jenkins.url": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).Url, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.mode": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).Mode, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.quietingDown": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).QuietingDown, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.plugins": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).Plugins, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jenkins.jobs": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).Jobs, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jenkins.nodes": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).Nodes, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jenkins.credentials": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkins).Credentials, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jenkins.security.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsSecurity).__id, ok = v.Value.(string)
		return
	},
	"jenkins.security.securityEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsSecurity).SecurityEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.security.csrfProtectionEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsSecurity).CsrfProtectionEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.security.allowsAnonymousAdmin": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsSecurity).AllowsAnonymousAdmin, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.security.slaveAgentPort": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsSecurity).SlaveAgentPort, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jenkins.plugin.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).__id, ok = v.Value.(string)
		return
	},
	"jenkins.plugin.shortName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).ShortName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.plugin.longName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).LongName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.plugin.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.plugin.enabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).Enabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.plugin.active": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).Active, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.plugin.hasUpdate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).HasUpdate, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.plugin.url": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).Url, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.plugin.requiredCoreVersion": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsPlugin).RequiredCoreVersion, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.job.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).__id, ok = v.Value.(string)
		return
	},
	"jenkins.job.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.job.fullName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).FullName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.job.url": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).Url, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.job.class": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).Class, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.job.buildable": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).Buildable, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.job.disabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).Disabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.job.lastBuildNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).LastBuildNumber, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jenkins.job.lastSuccessfulBuildNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).LastSuccessfulBuildNumber, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jenkins.job.lastFailedBuildNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).LastFailedBuildNumber, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jenkins.job.description": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).Description, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.job.node": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsJob).Node, ok = plugin.RawToTValue[*mqlJenkinsNode](v.Value, v.Error)
		return
	},
	"jenkins.node.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).__id, ok = v.Value.(string)
		return
	},
	"jenkins.node.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.node.description": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).Description, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.node.isController": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).IsController, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.node.offline": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).Offline, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.node.temporarilyOffline": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).TemporarilyOffline, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jenkins.node.offlineCauseReason": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).OfflineCauseReason, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.node.numExecutors": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).NumExecutors, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jenkins.node.labels": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsNode).Labels, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jenkins.credential.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsCredential).__id, ok = v.Value.(string)
		return
	},
	"jenkins.credential.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsCredential).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.credential.typeName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsCredential).TypeName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.credential.description": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsCredential).Description, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jenkins.credential.domain": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJenkinsCredential).Domain, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[jenkins] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[jenkins] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlJenkins for the jenkins resource
type mqlJenkins struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJenkinsInternal it will be used here
	Url          plugin.TValue[string]
	Version      plugin.TValue[string]
	Mode         plugin.TValue[string]
	QuietingDown plugin.TValue[bool]
	Plugins      plugin.TValue[[]any]
	Jobs         plugin.TValue[[]any]
	Nodes        plugin.TValue[[]any]
	Credentials  plugin.TValue[[]any]
}

// createJenkins creates a new instance of this resource
func createJenkins(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJenkins{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jenkins", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJenkins) MqlName() string {
	return "jenkins"
}

func (c *mqlJenkins) MqlID() string {
	return c.__id
}

func (c *mqlJenkins) GetUrl() *plugin.TValue[string] {
	return &c.Url
}

func (c *mqlJenkins) GetVersion() *plugin.TValue[string] {
	return &c.Version
}

func (c *mqlJenkins) GetMode() *plugin.TValue[string] {
	return &c.Mode
}

func (c *mqlJenkins) GetQuietingDown() *plugin.TValue[bool] {
	return &c.QuietingDown
}

func (c *mqlJenkins) GetPlugins() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Plugins, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jenkins", c.__id, "plugins")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.plugins()
	})
}

func (c *mqlJenkins) GetJobs() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Jobs, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jenkins", c.__id, "jobs")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.jobs()
	})
}

func (c *mqlJenkins) GetNodes() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Nodes, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jenkins", c.__id, "nodes")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.nodes()
	})
}

func (c *mqlJenkins) GetCredentials() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Credentials, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jenkins", c.__id, "credentials")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.credentials()
	})
}

// mqlJenkinsSecurity for the jenkins.security resource
type mqlJenkinsSecurity struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJenkinsSecurityInternal it will be used here
	SecurityEnabled       plugin.TValue[bool]
	CsrfProtectionEnabled plugin.TValue[bool]
	AllowsAnonymousAdmin  plugin.TValue[bool]
	SlaveAgentPort        plugin.TValue[int64]
}

// createJenkinsSecurity creates a new instance of this resource
func createJenkinsSecurity(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJenkinsSecurity{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jenkins.security", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJenkinsSecurity) MqlName() string {
	return "jenkins.security"
}

func (c *mqlJenkinsSecurity) MqlID() string {
	return c.__id
}

func (c *mqlJenkinsSecurity) GetSecurityEnabled() *plugin.TValue[bool] {
	return &c.SecurityEnabled
}

func (c *mqlJenkinsSecurity) GetCsrfProtectionEnabled() *plugin.TValue[bool] {
	return &c.CsrfProtectionEnabled
}

func (c *mqlJenkinsSecurity) GetAllowsAnonymousAdmin() *plugin.TValue[bool] {
	return &c.AllowsAnonymousAdmin
}

func (c *mqlJenkinsSecurity) GetSlaveAgentPort() *plugin.TValue[int64] {
	return &c.SlaveAgentPort
}

// mqlJenkinsPlugin for the jenkins.plugin resource
type mqlJenkinsPlugin struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJenkinsPluginInternal it will be used here
	ShortName           plugin.TValue[string]
	LongName            plugin.TValue[string]
	Version             plugin.TValue[string]
	Enabled             plugin.TValue[bool]
	Active              plugin.TValue[bool]
	HasUpdate           plugin.TValue[bool]
	Url                 plugin.TValue[string]
	RequiredCoreVersion plugin.TValue[string]
}

// createJenkinsPlugin creates a new instance of this resource
func createJenkinsPlugin(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJenkinsPlugin{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jenkins.plugin", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJenkinsPlugin) MqlName() string {
	return "jenkins.plugin"
}

func (c *mqlJenkinsPlugin) MqlID() string {
	return c.__id
}

func (c *mqlJenkinsPlugin) GetShortName() *plugin.TValue[string] {
	return &c.ShortName
}

func (c *mqlJenkinsPlugin) GetLongName() *plugin.TValue[string] {
	return &c.LongName
}

func (c *mqlJenkinsPlugin) GetVersion() *plugin.TValue[string] {
	return &c.Version
}

func (c *mqlJenkinsPlugin) GetEnabled() *plugin.TValue[bool] {
	return &c.Enabled
}

func (c *mqlJenkinsPlugin) GetActive() *plugin.TValue[bool] {
	return &c.Active
}

func (c *mqlJenkinsPlugin) GetHasUpdate() *plugin.TValue[bool] {
	return &c.HasUpdate
}

func (c *mqlJenkinsPlugin) GetUrl() *plugin.TValue[string] {
	return &c.Url
}

func (c *mqlJenkinsPlugin) GetRequiredCoreVersion() *plugin.TValue[string] {
	return &c.RequiredCoreVersion
}

// mqlJenkinsJob for the jenkins.job resource
type mqlJenkinsJob struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlJenkinsJobInternal
	Name                      plugin.TValue[string]
	FullName                  plugin.TValue[string]
	Url                       plugin.TValue[string]
	Class                     plugin.TValue[string]
	Buildable                 plugin.TValue[bool]
	Disabled                  plugin.TValue[bool]
	LastBuildNumber           plugin.TValue[int64]
	LastSuccessfulBuildNumber plugin.TValue[int64]
	LastFailedBuildNumber     plugin.TValue[int64]
	Description               plugin.TValue[string]
	Node                      plugin.TValue[*mqlJenkinsNode]
}

// createJenkinsJob creates a new instance of this resource
func createJenkinsJob(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJenkinsJob{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jenkins.job", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJenkinsJob) MqlName() string {
	return "jenkins.job"
}

func (c *mqlJenkinsJob) MqlID() string {
	return c.__id
}

func (c *mqlJenkinsJob) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlJenkinsJob) GetFullName() *plugin.TValue[string] {
	return &c.FullName
}

func (c *mqlJenkinsJob) GetUrl() *plugin.TValue[string] {
	return &c.Url
}

func (c *mqlJenkinsJob) GetClass() *plugin.TValue[string] {
	return &c.Class
}

func (c *mqlJenkinsJob) GetBuildable() *plugin.TValue[bool] {
	return &c.Buildable
}

func (c *mqlJenkinsJob) GetDisabled() *plugin.TValue[bool] {
	return &c.Disabled
}

func (c *mqlJenkinsJob) GetLastBuildNumber() *plugin.TValue[int64] {
	return &c.LastBuildNumber
}

func (c *mqlJenkinsJob) GetLastSuccessfulBuildNumber() *plugin.TValue[int64] {
	return &c.LastSuccessfulBuildNumber
}

func (c *mqlJenkinsJob) GetLastFailedBuildNumber() *plugin.TValue[int64] {
	return &c.LastFailedBuildNumber
}

func (c *mqlJenkinsJob) GetDescription() *plugin.TValue[string] {
	return &c.Description
}

func (c *mqlJenkinsJob) GetNode() *plugin.TValue[*mqlJenkinsNode] {
	return plugin.GetOrCompute[*mqlJenkinsNode](&c.Node, func() (*mqlJenkinsNode, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jenkins.job", c.__id, "node")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlJenkinsNode), nil
			}
		}

		return c.node()
	})
}

// mqlJenkinsNode for the jenkins.node resource
type mqlJenkinsNode struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJenkinsNodeInternal it will be used here
	Name               plugin.TValue[string]
	Description        plugin.TValue[string]
	IsController       plugin.TValue[bool]
	Offline            plugin.TValue[bool]
	TemporarilyOffline plugin.TValue[bool]
	OfflineCauseReason plugin.TValue[string]
	NumExecutors       plugin.TValue[int64]
	Labels             plugin.TValue[[]any]
}

// createJenkinsNode creates a new instance of this resource
func createJenkinsNode(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJenkinsNode{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jenkins.node", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJenkinsNode) MqlName() string {
	return "jenkins.node"
}

func (c *mqlJenkinsNode) MqlID() string {
	return c.__id
}

func (c *mqlJenkinsNode) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlJenkinsNode) GetDescription() *plugin.TValue[string] {
	return &c.Description
}

func (c *mqlJenkinsNode) GetIsController() *plugin.TValue[bool] {
	return &c.IsController
}

func (c *mqlJenkinsNode) GetOffline() *plugin.TValue[bool] {
	return &c.Offline
}

func (c *mqlJenkinsNode) GetTemporarilyOffline() *plugin.TValue[bool] {
	return &c.TemporarilyOffline
}

func (c *mqlJenkinsNode) GetOfflineCauseReason() *plugin.TValue[string] {
	return &c.OfflineCauseReason
}

func (c *mqlJenkinsNode) GetNumExecutors() *plugin.TValue[int64] {
	return &c.NumExecutors
}

func (c *mqlJenkinsNode) GetLabels() *plugin.TValue[[]any] {
	return &c.Labels
}

// mqlJenkinsCredential for the jenkins.credential resource
type mqlJenkinsCredential struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJenkinsCredentialInternal it will be used here
	Id          plugin.TValue[string]
	TypeName    plugin.TValue[string]
	Description plugin.TValue[string]
	Domain      plugin.TValue[string]
}

// createJenkinsCredential creates a new instance of this resource
func createJenkinsCredential(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJenkinsCredential{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jenkins.credential", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJenkinsCredential) MqlName() string {
	return "jenkins.credential"
}

func (c *mqlJenkinsCredential) MqlID() string {
	return c.__id
}

func (c *mqlJenkinsCredential) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlJenkinsCredential) GetTypeName() *plugin.TValue[string] {
	return &c.TypeName
}

func (c *mqlJenkinsCredential) GetDescription() *plugin.TValue[string] {
	return &c.Description
}

func (c *mqlJenkinsCredential) GetDomain() *plugin.TValue[string] {
	return &c.Domain
}
