// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"
	"time"

	"go.mondoo.com/mql/v13/llx"
	"go.mondoo.com/mql/v13/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/v13/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourceRippling             string = "rippling"
	ResourceRipplingCompany      string = "rippling.company"
	ResourceRipplingEmployee     string = "rippling.employee"
	ResourceRipplingDepartment   string = "rippling.department"
	ResourceRipplingTeam         string = "rippling.team"
	ResourceRipplingWorkLocation string = "rippling.workLocation"
	ResourceRipplingGroup        string = "rippling.group"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"rippling": {
			// to override args, implement: initRippling(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createRippling,
		},
		"rippling.company": {
			// to override args, implement: initRipplingCompany(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createRipplingCompany,
		},
		"rippling.employee": {
			Init:   initRipplingEmployee,
			Create: createRipplingEmployee,
		},
		"rippling.department": {
			Init:   initRipplingDepartment,
			Create: createRipplingDepartment,
		},
		"rippling.team": {
			Init:   initRipplingTeam,
			Create: createRipplingTeam,
		},
		"rippling.workLocation": {
			Init:   initRipplingWorkLocation,
			Create: createRipplingWorkLocation,
		},
		"rippling.group": {
			Init:   initRipplingGroup,
			Create: createRipplingGroup,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"rippling.companies": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRippling).GetCompanies()).ToDataRes(types.Array(types.Resource("rippling.company")))
	},
	"rippling.employees": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRippling).GetEmployees()).ToDataRes(types.Array(types.Resource("rippling.employee")))
	},
	"rippling.departments": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRippling).GetDepartments()).ToDataRes(types.Array(types.Resource("rippling.department")))
	},
	"rippling.teams": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRippling).GetTeams()).ToDataRes(types.Array(types.Resource("rippling.team")))
	},
	"rippling.workLocations": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRippling).GetWorkLocations()).ToDataRes(types.Array(types.Resource("rippling.workLocation")))
	},
	"rippling.groups": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRippling).GetGroups()).ToDataRes(types.Array(types.Resource("rippling.group")))
	},
	"rippling.company.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetId()).ToDataRes(types.String)
	},
	"rippling.company.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetName()).ToDataRes(types.String)
	},
	"rippling.company.legalName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetLegalName()).ToDataRes(types.String)
	},
	"rippling.company.workEmail": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetWorkEmail()).ToDataRes(types.String)
	},
	"rippling.company.phone": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetPhone()).ToDataRes(types.String)
	},
	"rippling.company.primaryEmail": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetPrimaryEmail()).ToDataRes(types.String)
	},
	"rippling.company.tin": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetTin()).ToDataRes(types.String)
	},
	"rippling.company.needsOnboarding": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetNeedsOnboarding()).ToDataRes(types.Bool)
	},
	"rippling.company.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetCreatedAt()).ToDataRes(types.Time)
	},
	"rippling.company.streetLine1": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetStreetLine1()).ToDataRes(types.String)
	},
	"rippling.company.streetLine2": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetStreetLine2()).ToDataRes(types.String)
	},
	"rippling.company.city": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetCity()).ToDataRes(types.String)
	},
	"rippling.company.state": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetState()).ToDataRes(types.String)
	},
	"rippling.company.zip": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetZip()).ToDataRes(types.String)
	},
	"rippling.company.country": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingCompany).GetCountry()).ToDataRes(types.String)
	},
	"rippling.employee.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetId()).ToDataRes(types.String)
	},
	"rippling.employee.employeeNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetEmployeeNumber()).ToDataRes(types.Int)
	},
	"rippling.employee.firstName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetFirstName()).ToDataRes(types.String)
	},
	"rippling.employee.middleName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetMiddleName()).ToDataRes(types.String)
	},
	"rippling.employee.lastName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetLastName()).ToDataRes(types.String)
	},
	"rippling.employee.preferredFirstName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetPreferredFirstName()).ToDataRes(types.String)
	},
	"rippling.employee.workEmail": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetWorkEmail()).ToDataRes(types.String)
	},
	"rippling.employee.personalEmail": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetPersonalEmail()).ToDataRes(types.String)
	},
	"rippling.employee.phoneNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetPhoneNumber()).ToDataRes(types.String)
	},
	"rippling.employee.title": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetTitle()).ToDataRes(types.String)
	},
	"rippling.employee.employmentType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetEmploymentType()).ToDataRes(types.String)
	},
	"rippling.employee.roleStatus": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetRoleStatus()).ToDataRes(types.String)
	},
	"rippling.employee.terminated": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetTerminated()).ToDataRes(types.Bool)
	},
	"rippling.employee.startDate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetStartDate()).ToDataRes(types.Time)
	},
	"rippling.employee.endDate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetEndDate()).ToDataRes(types.Time)
	},
	"rippling.employee.terminationDate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetTerminationDate()).ToDataRes(types.Time)
	},
	"rippling.employee.terminationType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetTerminationType()).ToDataRes(types.String)
	},
	"rippling.employee.terminationReason": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetTerminationReason()).ToDataRes(types.String)
	},
	"rippling.employee.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetCreatedAt()).ToDataRes(types.Time)
	},
	"rippling.employee.updatedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetUpdatedAt()).ToDataRes(types.Time)
	},
	"rippling.employee.manager": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetManager()).ToDataRes(types.Resource("rippling.employee"))
	},
	"rippling.employee.department": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetDepartment()).ToDataRes(types.Resource("rippling.department"))
	},
	"rippling.employee.team": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetTeam()).ToDataRes(types.Resource("rippling.team"))
	},
	"rippling.employee.workLocation": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingEmployee).GetWorkLocation()).ToDataRes(types.Resource("rippling.workLocation"))
	},
	"rippling.department.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingDepartment).GetId()).ToDataRes(types.String)
	},
	"rippling.department.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingDepartment).GetName()).ToDataRes(types.String)
	},
	"rippling.department.parent": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingDepartment).GetParent()).ToDataRes(types.Resource("rippling.department"))
	},
	"rippling.department.employees": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingDepartment).GetEmployees()).ToDataRes(types.Array(types.Resource("rippling.employee")))
	},
	"rippling.team.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingTeam).GetId()).ToDataRes(types.String)
	},
	"rippling.team.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingTeam).GetName()).ToDataRes(types.String)
	},
	"rippling.team.parentTeam": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingTeam).GetParentTeam()).ToDataRes(types.Resource("rippling.team"))
	},
	"rippling.team.employees": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingTeam).GetEmployees()).ToDataRes(types.Array(types.Resource("rippling.employee")))
	},
	"rippling.workLocation.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetId()).ToDataRes(types.String)
	},
	"rippling.workLocation.nickname": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetNickname()).ToDataRes(types.String)
	},
	"rippling.workLocation.phone": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetPhone()).ToDataRes(types.String)
	},
	"rippling.workLocation.streetLine1": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetStreetLine1()).ToDataRes(types.String)
	},
	"rippling.workLocation.streetLine2": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetStreetLine2()).ToDataRes(types.String)
	},
	"rippling.workLocation.city": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetCity()).ToDataRes(types.String)
	},
	"rippling.workLocation.state": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetState()).ToDataRes(types.String)
	},
	"rippling.workLocation.zip": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetZip()).ToDataRes(types.String)
	},
	"rippling.workLocation.country": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetCountry()).ToDataRes(types.String)
	},
	"rippling.workLocation.employees": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingWorkLocation).GetEmployees()).ToDataRes(types.Array(types.Resource("rippling.employee")))
	},
	"rippling.group.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingGroup).GetId()).ToDataRes(types.String)
	},
	"rippling.group.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingGroup).GetName()).ToDataRes(types.String)
	},
	"rippling.group.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingGroup).GetVersion()).ToDataRes(types.String)
	},
	"rippling.group.members": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlRipplingGroup).GetMembers()).ToDataRes(types.Array(types.Resource("rippling.employee")))
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"rippling.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRippling).__id, ok = v.Value.(string)
		return
	},
	"rippling.companies": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRippling).Companies, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.employees": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRippling).Employees, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.departments": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRippling).Departments, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.teams": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRippling).Teams, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.workLocations": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRippling).WorkLocations, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.groups": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRippling).Groups, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.company.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).__id, ok = v.Value.(string)
		return
	},
	"rippling.company.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.legalName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).LegalName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.workEmail": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).WorkEmail, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.phone": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).Phone, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.primaryEmail": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).PrimaryEmail, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.tin": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).Tin, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.needsOnboarding": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).NeedsOnboarding, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"rippling.company.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"rippling.company.streetLine1": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).StreetLine1, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.streetLine2": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).StreetLine2, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.city": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).City, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.state": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).State, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.zip": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).Zip, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.company.country": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingCompany).Country, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).__id, ok = v.Value.(string)
		return
	},
	"rippling.employee.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.employeeNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).EmployeeNumber, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"rippling.employee.firstName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).FirstName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.middleName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).MiddleName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.lastName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).LastName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.preferredFirstName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).PreferredFirstName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.workEmail": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).WorkEmail, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.personalEmail": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).PersonalEmail, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.phoneNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).PhoneNumber, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.title": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).Title, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.employmentType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).EmploymentType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.roleStatus": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).RoleStatus, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.terminated": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).Terminated, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"rippling.employee.startDate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).StartDate, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"rippling.employee.endDate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).EndDate, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"rippling.employee.terminationDate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).TerminationDate, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"rippling.employee.terminationType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).TerminationType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.terminationReason": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).TerminationReason, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.employee.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"rippling.employee.updatedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).UpdatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"rippling.employee.manager": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).Manager, ok = plugin.RawToTValue[*mqlRipplingEmployee](v.Value, v.Error)
		return
	},
	"rippling.employee.department": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).Department, ok = plugin.RawToTValue[*mqlRipplingDepartment](v.Value, v.Error)
		return
	},
	"rippling.employee.team": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).Team, ok = plugin.RawToTValue[*mqlRipplingTeam](v.Value, v.Error)
		return
	},
	"rippling.employee.workLocation": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingEmployee).WorkLocation, ok = plugin.RawToTValue[*mqlRipplingWorkLocation](v.Value, v.Error)
		return
	},
	"rippling.department.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingDepartment).__id, ok = v.Value.(string)
		return
	},
	"rippling.department.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingDepartment).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.department.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingDepartment).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.department.parent": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingDepartment).Parent, ok = plugin.RawToTValue[*mqlRipplingDepartment](v.Value, v.Error)
		return
	},
	"rippling.department.employees": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingDepartment).Employees, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.team.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingTeam).__id, ok = v.Value.(string)
		return
	},
	"rippling.team.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingTeam).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.team.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingTeam).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.team.parentTeam": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingTeam).ParentTeam, ok = plugin.RawToTValue[*mqlRipplingTeam](v.Value, v.Error)
		return
	},
	"rippling.team.employees": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingTeam).Employees, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.workLocation.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).__id, ok = v.Value.(string)
		return
	},
	"rippling.workLocation.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.nickname": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).Nickname, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.phone": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).Phone, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.streetLine1": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).StreetLine1, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.streetLine2": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).StreetLine2, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.city": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).City, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.state": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).State, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.zip": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).Zip, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.country": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).Country, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.workLocation.employees": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingWorkLocation).Employees, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"rippling.group.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingGroup).__id, ok = v.Value.(string)
		return
	},
	"rippling.group.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingGroup).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.group.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingGroup).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.group.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingGroup).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"rippling.group.members": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlRipplingGroup).Members, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[rippling] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[rippling] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlRippling for the rippling resource
type mqlRippling struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlRipplingInternal it will be used here
	Companies     plugin.TValue[[]any]
	Employees     plugin.TValue[[]any]
	Departments   plugin.TValue[[]any]
	Teams         plugin.TValue[[]any]
	WorkLocations plugin.TValue[[]any]
	Groups        plugin.TValue[[]any]
}

// createRippling creates a new instance of this resource
func createRippling(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlRippling{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("rippling", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlRippling) MqlName() string {
	return "rippling"
}

func (c *mqlRippling) MqlID() string {
	return c.__id
}

func (c *mqlRippling) GetCompanies() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Companies, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling", c.__id, "companies")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.companies()
	})
}

func (c *mqlRippling) GetEmployees() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Employees, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling", c.__id, "employees")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.employees()
	})
}

func (c *mqlRippling) GetDepartments() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Departments, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling", c.__id, "departments")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.departments()
	})
}

func (c *mqlRippling) GetTeams() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Teams, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling", c.__id, "teams")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.teams()
	})
}

func (c *mqlRippling) GetWorkLocations() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.WorkLocations, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling", c.__id, "workLocations")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.workLocations()
	})
}

func (c *mqlRippling) GetGroups() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Groups, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling", c.__id, "groups")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.groups()
	})
}

// mqlRipplingCompany for the rippling.company resource
type mqlRipplingCompany struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlRipplingCompanyInternal it will be used here
	Id              plugin.TValue[string]
	Name            plugin.TValue[string]
	LegalName       plugin.TValue[string]
	WorkEmail       plugin.TValue[string]
	Phone           plugin.TValue[string]
	PrimaryEmail    plugin.TValue[string]
	Tin             plugin.TValue[string]
	NeedsOnboarding plugin.TValue[bool]
	CreatedAt       plugin.TValue[*time.Time]
	StreetLine1     plugin.TValue[string]
	StreetLine2     plugin.TValue[string]
	City            plugin.TValue[string]
	State           plugin.TValue[string]
	Zip             plugin.TValue[string]
	Country         plugin.TValue[string]
}

// createRipplingCompany creates a new instance of this resource
func createRipplingCompany(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlRipplingCompany{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("rippling.company", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlRipplingCompany) MqlName() string {
	return "rippling.company"
}

func (c *mqlRipplingCompany) MqlID() string {
	return c.__id
}

func (c *mqlRipplingCompany) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlRipplingCompany) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlRipplingCompany) GetLegalName() *plugin.TValue[string] {
	return &c.LegalName
}

func (c *mqlRipplingCompany) GetWorkEmail() *plugin.TValue[string] {
	return &c.WorkEmail
}

func (c *mqlRipplingCompany) GetPhone() *plugin.TValue[string] {
	return &c.Phone
}

func (c *mqlRipplingCompany) GetPrimaryEmail() *plugin.TValue[string] {
	return &c.PrimaryEmail
}

func (c *mqlRipplingCompany) GetTin() *plugin.TValue[string] {
	return &c.Tin
}

func (c *mqlRipplingCompany) GetNeedsOnboarding() *plugin.TValue[bool] {
	return &c.NeedsOnboarding
}

func (c *mqlRipplingCompany) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlRipplingCompany) GetStreetLine1() *plugin.TValue[string] {
	return &c.StreetLine1
}

func (c *mqlRipplingCompany) GetStreetLine2() *plugin.TValue[string] {
	return &c.StreetLine2
}

func (c *mqlRipplingCompany) GetCity() *plugin.TValue[string] {
	return &c.City
}

func (c *mqlRipplingCompany) GetState() *plugin.TValue[string] {
	return &c.State
}

func (c *mqlRipplingCompany) GetZip() *plugin.TValue[string] {
	return &c.Zip
}

func (c *mqlRipplingCompany) GetCountry() *plugin.TValue[string] {
	return &c.Country
}

// mqlRipplingEmployee for the rippling.employee resource
type mqlRipplingEmployee struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlRipplingEmployeeInternal
	Id                 plugin.TValue[string]
	EmployeeNumber     plugin.TValue[int64]
	FirstName          plugin.TValue[string]
	MiddleName         plugin.TValue[string]
	LastName           plugin.TValue[string]
	PreferredFirstName plugin.TValue[string]
	WorkEmail          plugin.TValue[string]
	PersonalEmail      plugin.TValue[string]
	PhoneNumber        plugin.TValue[string]
	Title              plugin.TValue[string]
	EmploymentType     plugin.TValue[string]
	RoleStatus         plugin.TValue[string]
	Terminated         plugin.TValue[bool]
	StartDate          plugin.TValue[*time.Time]
	EndDate            plugin.TValue[*time.Time]
	TerminationDate    plugin.TValue[*time.Time]
	TerminationType    plugin.TValue[string]
	TerminationReason  plugin.TValue[string]
	CreatedAt          plugin.TValue[*time.Time]
	UpdatedAt          plugin.TValue[*time.Time]
	Manager            plugin.TValue[*mqlRipplingEmployee]
	Department         plugin.TValue[*mqlRipplingDepartment]
	Team               plugin.TValue[*mqlRipplingTeam]
	WorkLocation       plugin.TValue[*mqlRipplingWorkLocation]
}

// createRipplingEmployee creates a new instance of this resource
func createRipplingEmployee(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlRipplingEmployee{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("rippling.employee", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlRipplingEmployee) MqlName() string {
	return "rippling.employee"
}

func (c *mqlRipplingEmployee) MqlID() string {
	return c.__id
}

func (c *mqlRipplingEmployee) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlRipplingEmployee) GetEmployeeNumber() *plugin.TValue[int64] {
	return &c.EmployeeNumber
}

func (c *mqlRipplingEmployee) GetFirstName() *plugin.TValue[string] {
	return &c.FirstName
}

func (c *mqlRipplingEmployee) GetMiddleName() *plugin.TValue[string] {
	return &c.MiddleName
}

func (c *mqlRipplingEmployee) GetLastName() *plugin.TValue[string] {
	return &c.LastName
}

func (c *mqlRipplingEmployee) GetPreferredFirstName() *plugin.TValue[string] {
	return &c.PreferredFirstName
}

func (c *mqlRipplingEmployee) GetWorkEmail() *plugin.TValue[string] {
	return &c.WorkEmail
}

func (c *mqlRipplingEmployee) GetPersonalEmail() *plugin.TValue[string] {
	return &c.PersonalEmail
}

func (c *mqlRipplingEmployee) GetPhoneNumber() *plugin.TValue[string] {
	return &c.PhoneNumber
}

func (c *mqlRipplingEmployee) GetTitle() *plugin.TValue[string] {
	return &c.Title
}

func (c *mqlRipplingEmployee) GetEmploymentType() *plugin.TValue[string] {
	return &c.EmploymentType
}

func (c *mqlRipplingEmployee) GetRoleStatus() *plugin.TValue[string] {
	return &c.RoleStatus
}

func (c *mqlRipplingEmployee) GetTerminated() *plugin.TValue[bool] {
	return &c.Terminated
}

func (c *mqlRipplingEmployee) GetStartDate() *plugin.TValue[*time.Time] {
	return &c.StartDate
}

func (c *mqlRipplingEmployee) GetEndDate() *plugin.TValue[*time.Time] {
	return &c.EndDate
}

func (c *mqlRipplingEmployee) GetTerminationDate() *plugin.TValue[*time.Time] {
	return &c.TerminationDate
}

func (c *mqlRipplingEmployee) GetTerminationType() *plugin.TValue[string] {
	return &c.TerminationType
}

func (c *mqlRipplingEmployee) GetTerminationReason() *plugin.TValue[string] {
	return &c.TerminationReason
}

func (c *mqlRipplingEmployee) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlRipplingEmployee) GetUpdatedAt() *plugin.TValue[*time.Time] {
	return &c.UpdatedAt
}

func (c *mqlRipplingEmployee) GetManager() *plugin.TValue[*mqlRipplingEmployee] {
	return plugin.GetOrCompute[*mqlRipplingEmployee](&c.Manager, func() (*mqlRipplingEmployee, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.employee", c.__id, "manager")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlRipplingEmployee), nil
			}
		}

		return c.manager()
	})
}

func (c *mqlRipplingEmployee) GetDepartment() *plugin.TValue[*mqlRipplingDepartment] {
	return plugin.GetOrCompute[*mqlRipplingDepartment](&c.Department, func() (*mqlRipplingDepartment, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.employee", c.__id, "department")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlRipplingDepartment), nil
			}
		}

		return c.department()
	})
}

func (c *mqlRipplingEmployee) GetTeam() *plugin.TValue[*mqlRipplingTeam] {
	return plugin.GetOrCompute[*mqlRipplingTeam](&c.Team, func() (*mqlRipplingTeam, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.employee", c.__id, "team")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlRipplingTeam), nil
			}
		}

		return c.team()
	})
}

func (c *mqlRipplingEmployee) GetWorkLocation() *plugin.TValue[*mqlRipplingWorkLocation] {
	return plugin.GetOrCompute[*mqlRipplingWorkLocation](&c.WorkLocation, func() (*mqlRipplingWorkLocation, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.employee", c.__id, "workLocation")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlRipplingWorkLocation), nil
			}
		}

		return c.workLocation()
	})
}

// mqlRipplingDepartment for the rippling.department resource
type mqlRipplingDepartment struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlRipplingDepartmentInternal
	Id        plugin.TValue[string]
	Name      plugin.TValue[string]
	Parent    plugin.TValue[*mqlRipplingDepartment]
	Employees plugin.TValue[[]any]
}

// createRipplingDepartment creates a new instance of this resource
func createRipplingDepartment(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlRipplingDepartment{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("rippling.department", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlRipplingDepartment) MqlName() string {
	return "rippling.department"
}

func (c *mqlRipplingDepartment) MqlID() string {
	return c.__id
}

func (c *mqlRipplingDepartment) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlRipplingDepartment) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlRipplingDepartment) GetParent() *plugin.TValue[*mqlRipplingDepartment] {
	return plugin.GetOrCompute[*mqlRipplingDepartment](&c.Parent, func() (*mqlRipplingDepartment, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.department", c.__id, "parent")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlRipplingDepartment), nil
			}
		}

		return c.parent()
	})
}

func (c *mqlRipplingDepartment) GetEmployees() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Employees, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.department", c.__id, "employees")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.employees()
	})
}

// mqlRipplingTeam for the rippling.team resource
type mqlRipplingTeam struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlRipplingTeamInternal
	Id         plugin.TValue[string]
	Name       plugin.TValue[string]
	ParentTeam plugin.TValue[*mqlRipplingTeam]
	Employees  plugin.TValue[[]any]
}

// createRipplingTeam creates a new instance of this resource
func createRipplingTeam(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlRipplingTeam{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("rippling.team", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlRipplingTeam) MqlName() string {
	return "rippling.team"
}

func (c *mqlRipplingTeam) MqlID() string {
	return c.__id
}

func (c *mqlRipplingTeam) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlRipplingTeam) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlRipplingTeam) GetParentTeam() *plugin.TValue[*mqlRipplingTeam] {
	return plugin.GetOrCompute[*mqlRipplingTeam](&c.ParentTeam, func() (*mqlRipplingTeam, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.team", c.__id, "parentTeam")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlRipplingTeam), nil
			}
		}

		return c.parentTeam()
	})
}

func (c *mqlRipplingTeam) GetEmployees() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Employees, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.team", c.__id, "employees")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.employees()
	})
}

// mqlRipplingWorkLocation for the rippling.workLocation resource
type mqlRipplingWorkLocation struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlRipplingWorkLocationInternal it will be used here
	Id          plugin.TValue[string]
	Nickname    plugin.TValue[string]
	Phone       plugin.TValue[string]
	StreetLine1 plugin.TValue[string]
	StreetLine2 plugin.TValue[string]
	City        plugin.TValue[string]
	State       plugin.TValue[string]
	Zip         plugin.TValue[string]
	Country     plugin.TValue[string]
	Employees   plugin.TValue[[]any]
}

// createRipplingWorkLocation creates a new instance of this resource
func createRipplingWorkLocation(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlRipplingWorkLocation{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("rippling.workLocation", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlRipplingWorkLocation) MqlName() string {
	return "rippling.workLocation"
}

func (c *mqlRipplingWorkLocation) MqlID() string {
	return c.__id
}

func (c *mqlRipplingWorkLocation) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlRipplingWorkLocation) GetNickname() *plugin.TValue[string] {
	return &c.Nickname
}

func (c *mqlRipplingWorkLocation) GetPhone() *plugin.TValue[string] {
	return &c.Phone
}

func (c *mqlRipplingWorkLocation) GetStreetLine1() *plugin.TValue[string] {
	return &c.StreetLine1
}

func (c *mqlRipplingWorkLocation) GetStreetLine2() *plugin.TValue[string] {
	return &c.StreetLine2
}

func (c *mqlRipplingWorkLocation) GetCity() *plugin.TValue[string] {
	return &c.City
}

func (c *mqlRipplingWorkLocation) GetState() *plugin.TValue[string] {
	return &c.State
}

func (c *mqlRipplingWorkLocation) GetZip() *plugin.TValue[string] {
	return &c.Zip
}

func (c *mqlRipplingWorkLocation) GetCountry() *plugin.TValue[string] {
	return &c.Country
}

func (c *mqlRipplingWorkLocation) GetEmployees() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Employees, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.workLocation", c.__id, "employees")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.employees()
	})
}

// mqlRipplingGroup for the rippling.group resource
type mqlRipplingGroup struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlRipplingGroupInternal
	Id      plugin.TValue[string]
	Name    plugin.TValue[string]
	Version plugin.TValue[string]
	Members plugin.TValue[[]any]
}

// createRipplingGroup creates a new instance of this resource
func createRipplingGroup(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlRipplingGroup{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("rippling.group", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlRipplingGroup) MqlName() string {
	return "rippling.group"
}

func (c *mqlRipplingGroup) MqlID() string {
	return c.__id
}

func (c *mqlRipplingGroup) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlRipplingGroup) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlRipplingGroup) GetVersion() *plugin.TValue[string] {
	return &c.Version
}

func (c *mqlRipplingGroup) GetMembers() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Members, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("rippling.group", c.__id, "members")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.members()
	})
}
