// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package networkinterface

import (
	"io"
	"net"
	"sort"
	"strings"

	"github.com/cockroachdb/errors"
	"go.mondoo.com/mql/providers-sdk/v1/inventory"
	"go.mondoo.com/mql/providers/os/connection/shared"
	"go.mondoo.com/mql/providers/os/resources/powershell"
)

// Route represents a network route entry
type Route struct {
	Destination string
	Gateway     string
	Flags       []string
	Interface   string
	Platform    *inventory.Platform // Platform-specific flag handling

	// The fields below describe where a route lives and who installed it.
	// They come from `ip -json route show table all` on Linux and stay empty
	// on the sources that do not report them. A host that uses VRFs needs
	// Table to tell two routes for the same prefix apart.

	// Table is the routing table of the route, as a name or a numeric id
	// (e.g. main, local, 1005).
	Table string
	// Protocol is what installed the route (e.g. kernel, boot, static, bgp).
	Protocol string
	// Scope is the scope of the route (e.g. global, link, host).
	Scope string
	// Metric is the route priority. A lower value wins.
	Metric int64
	// Source is the preferred source address of the route (prefsrc).
	Source string
	// Type is the route type (e.g. unicast, blackhole, unreachable).
	Type string
}

// operatingSystemRouteDetector is an interface for platform-specific route detection
type operatingSystemRouteDetector interface {
	// List returns a list of Routes
	List() ([]Route, error)
}

// darwinRouteDetector detects network routes on macOS/Darwin systems
type darwinRouteDetector struct {
	conn     shared.Connection
	platform *inventory.Platform
}

// linuxRouteDetector detects network routes on Linux systems
type linuxRouteDetector struct {
	conn     shared.Connection
	platform *inventory.Platform
}

// windowsRouteDetector detects network routes on Windows systems
type windowsRouteDetector struct {
	conn     shared.Connection
	platform *inventory.Platform
}

// Routes returns the network routes of the system.
// This function dispatches to platform-specific implementations based on runtime detection.
func Routes(conn shared.Connection, pf *inventory.Platform) ([]Route, error) {
	var detector operatingSystemRouteDetector

	switch {
	case pf.IsFamily(inventory.FAMILY_LINUX):
		detector = &linuxRouteDetector{conn: conn, platform: pf}
	case pf.IsFamily(inventory.FAMILY_DARWIN):
		detector = &darwinRouteDetector{conn: conn, platform: pf}
	case pf.IsFamily(inventory.FAMILY_WINDOWS):
		detector = &windowsRouteDetector{conn: conn, platform: pf}
	default:
		return nil, errors.New("your platform is not supported for the detection of network routes")
	}

	return detector.List()
}

// IsDefaultRoute checks if a route is a default route (destination is 0.0.0.0/0 or ::/0)
func (r *Route) IsDefaultRoute() bool {
	return r.Destination == "0.0.0.0" || r.Destination == "0.0.0.0/0" ||
		r.Destination == "::" || r.Destination == "::/0" || r.Destination == "default"
}

// IsIPv4 checks if the route's gateway is an IPv4 address
func (r *Route) IsIPv4() bool {
	if r.Gateway == "" {
		return false
	}
	ip := net.ParseIP(r.Gateway)
	if ip == nil {
		return false
	}
	return ip.To4() != nil
}

// IsIPv6 checks if the route's gateway is an IPv6 address
func (r *Route) IsIPv6() bool {
	if r.Gateway == "" {
		return false
	}
	ip := net.ParseIP(r.Gateway)
	if ip == nil {
		return false
	}
	return ip.To4() == nil && ip.To16() != nil
}

// bsdRouteFlagsMap maps route flag bits to their human-readable names on
// BSD-derived systems, per sys/route.h. macOS uses these.
//
// Linux does NOT: its RTF_* values in include/uapi/linux/route.h agree only up
// to RTF_HOST (0x4) and diverge from 0x8 onwards, so Linux routes must be
// decoded with linuxRouteFlagsMap instead.
var bsdRouteFlagsMap = map[int64]string{
	0x1:       "UP",        // RTF_UP - route is up
	0x2:       "GATEWAY",   // RTF_GATEWAY - route has a gateway
	0x4:       "HOST",      // RTF_HOST - host route (not a network route)
	0x8:       "REJECT",    // RTF_REJECT - reject route
	0x10:      "DYNAMIC",   // RTF_DYNAMIC - dynamically installed
	0x20:      "MODIFIED",  // RTF_MODIFIED - modified by redirect
	0x40:      "DONE",      // RTF_DONE - message confirmed
	0x80:      "MASK",      // RTF_MASK - subnet mask present
	0x100:     "CLONING",   // RTF_CLONING - generate new routes on use
	0x200:     "XRESOLVE",  // RTF_XRESOLVE - external daemon resolves name
	0x400:     "LLINFO",    // RTF_LLINFO - generated by link layer
	0x800:     "STATIC",    // RTF_STATIC - manually added
	0x1000:    "BLACKHOLE", // RTF_BLACKHOLE - just discard pkts
	0x2000:    "PROTO1",    // RTF_PROTO1 - protocol specific routing flag #1
	0x4000:    "PROTO2",    // RTF_PROTO2 - protocol specific routing flag #2
	0x40000:   "PROTO3",    // RTF_PROTO3 - protocol specific routing flag #3
	0x20000:   "WASCLONED", // RTF_WASCLONED - route generated through cloning
	0x100000:  "PRCLONING", // RTF_PRCLONING - protocol requires cloning
	0x1000000: "PINNED",    // RTF_PINNED - future use
	0x2000000: "LOCAL",     // RTF_LOCAL - route represents a local address
	0x4000000: "BROADCAST", // RTF_BROADCAST - route represents a broadcast address
	0x8000000: "MULTICAST", // RTF_MULTICAST - route represents a multicast address
}

// linuxRouteFlagsMap maps the RTF_* bits of /proc/net/route to their names, per
// include/uapi/linux/route.h. These are the IPv4 flags; the IPv6 table below
// builds on them.
var linuxRouteFlagsMap = map[int64]string{
	0x0001: "UP",        // RTF_UP - route is usable
	0x0002: "GATEWAY",   // RTF_GATEWAY - destination is a gateway
	0x0004: "HOST",      // RTF_HOST - host entry, network otherwise
	0x0008: "REINSTATE", // RTF_REINSTATE - reinstate route after timeout
	0x0010: "DYNAMIC",   // RTF_DYNAMIC - created dynamically by a redirect
	0x0020: "MODIFIED",  // RTF_MODIFIED - modified dynamically by a redirect
	0x0040: "MTU",       // RTF_MTU - route carries a specific MTU
	0x0080: "WINDOW",    // RTF_WINDOW - per route window clamping
	0x0100: "IRTT",      // RTF_IRTT - initial round trip time
	0x0200: "REJECT",    // RTF_REJECT - packets to this destination are rejected
}

// linuxIPv6RouteFlagsMap maps the flag bits of /proc/net/ipv6_route. IPv6 reuses
// the low bits above and adds its own from include/uapi/linux/ipv6_route.h.
var linuxIPv6RouteFlagsMap = map[int64]string{
	0x00010000: "DEFAULT",   // RTF_DEFAULT - learned via router discovery
	0x00020000: "ALLONLINK", // RTF_ALLONLINK - no routers on link
	0x00040000: "ADDRCONF",  // RTF_ADDRCONF - installed from a router advertisement
	0x00080000: "PREFIX_RT", // RTF_PREFIX_RT - prefix-only route
	0x00100000: "ANYCAST",   // RTF_ANYCAST - anycast
	0x00200000: "NONEXTHOP", // RTF_NONEXTHOP - route with no next hop
	0x00400000: "EXPIRES",   // RTF_EXPIRES - route expires
	0x00800000: "ROUTEINFO", // RTF_ROUTEINFO - route information from an RA
	0x01000000: "CACHE",     // RTF_CACHE - cache entry
	0x02000000: "FLOW",      // RTF_FLOW - flow significant route
	0x04000000: "POLICY",    // RTF_POLICY - policy route
	0x40000000: "PCPU",      // RTF_PCPU - per-cpu, read only
	0x80000000: "LOCAL",     // RTF_LOCAL - route to a local address
}

func init() {
	// IPv6 routes carry the IPv4 bits too, so fold them in rather than
	// restating them and letting the two lists drift apart.
	for bit, name := range linuxRouteFlagsMap {
		linuxIPv6RouteFlagsMap[bit] = name
	}
}

// parseBSDRouteFlags converts the route flags of a BSD-derived system into an
// array of flag strings.
func parseBSDRouteFlags(flags int64) []string {
	return parseFlags(flags, bsdRouteFlagsMap)
}

// parseLinuxRouteFlags converts the flags column of /proc/net/route into an
// array of flag strings.
func parseLinuxRouteFlags(flags int64) []string {
	return parseFlags(flags, linuxRouteFlagsMap)
}

// parseLinuxIPv6RouteFlags converts the flags column of /proc/net/ipv6_route
// into an array of flag strings.
func parseLinuxIPv6RouteFlags(flags int64) []string {
	return parseFlags(flags, linuxIPv6RouteFlagsMap)
}

// routeFlagsRejected reports whether the route discards traffic rather than
// carrying it, which is what the kernel installs for an unreachable
// destination.
func routeFlagsRejected(flags []string) bool {
	for _, f := range flags {
		if f == "REJECT" || f == "BLACKHOLE" {
			return true
		}
	}
	return false
}

// parseFlags converts route flags integer to an array of flag strings using the provided flags map
func parseFlags(flags int64, flagsMap map[int64]string) []string {
	var flagStrings []string
	for bit, name := range flagsMap {
		if flags&bit != 0 {
			flagStrings = append(flagStrings, name)
		}
	}

	sort.Strings(flagStrings)
	return flagStrings
}

// runCommand is a helper function that executes commands and reads the standard output
func runCommand(conn shared.Connection, platform *inventory.Platform, commandString string) (string, error) {
	if platform.IsFamily(inventory.FAMILY_WINDOWS) {
		commandString = powershell.Encode(commandString)
	}
	cmd, err := conn.RunCommand(commandString)
	if err != nil {
		return "", err
	}

	data, err := io.ReadAll(cmd.Stdout)
	if err != nil {
		return "", err
	}

	return strings.TrimSpace(string(data)), nil
}
