# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# See https://golangci-lint.run/usage/configuration/ for configuration options
run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.lr\\.go$"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - gofmt
    - staticcheck
    - govet

linters-settings:
  gofmt:
    simplify: false

  govet:
    # enable or disable analyzers by name
    # run `go tool vet help` to see all analyzers
    enable:
      - structtag
      - lostcancel
    disable-all: true
