# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
project_name: cnquery
env:
  - CGO_ENABLED=0
before:
  hooks:
    - make providers
builds:
  - id: linux
    main: ./apps/cnquery/cnquery.go
    binary: cnquery
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
      - arm
      - ppc64le
    # ARM 6= Raspberry Pi A, A+, B, B+, Zero
    # ARM 7= Raspberry Pi 2, 3, 4
    goarm:
      - 6
      - 7
    flags:
      - -tags="production netgo"
    ldflags:
      - "-extldflags=-static"
      - -s -w -X go.mondoo.com/cnquery.Version={{.Version}} -X go.mondoo.com/cnquery.Build={{.ShortCommit}} -X go.mondoo.com/cnquery.Date={{.Date}}
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  disable: true
changelog:
  skip: true
dockers: # https://goreleaser.com/customization/docker/
    # UBI containers
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile-ubi
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi-amd64"
      - "mondoo/{{ .ProjectName }}:edge-latest-ubi-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=root"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile-ubi
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi-arm64"
      - "mondoo/{{ .ProjectName }}:edge-latest-ubi-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=root"
    # Standard containers
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-amd64"
      - "mondoo/{{ .ProjectName }}:edge-latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=root"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-arm64v8"
      - "mondoo/{{ .ProjectName }}:edge-latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=root"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-armv6"
      - "mondoo/{{ .ProjectName }}:edge-latest-armv6"
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=root"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-armv7"
      - "mondoo/{{ .ProjectName }}:edge-latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=root"
  # Rootless
    # UBI containers
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile-ubi
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi-amd64-rootless"
      - "mondoo/{{ .ProjectName }}:edge-latest-ubi-amd64-rootless"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=rootless"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile-ubi
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi-arm64-rootless"
      - "mondoo/{{ .ProjectName }}:edge-latest-ubi-arm64-rootless"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=rootless"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-amd64-rootless"
      - "mondoo/{{ .ProjectName }}:edge-latest-amd64-rootless"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=rootless"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-arm64v8-rootless"
      - "mondoo/{{ .ProjectName }}:edge-latest-arm64v8-rootless"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=rootless"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-armv6-rootless"
      - "mondoo/{{ .ProjectName }}:edge-latest-armv6-rootless"
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=rootless"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "mondoo/{{ .ProjectName }}:edge-{{ .Version }}-armv7-rootless"
      - "mondoo/{{ .ProjectName }}:edge-latest-armv7-rootless"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--target=rootless"
docker_manifests:  # https://goreleaser.com/customization/docker_manifest/
    # UBI containers
  - name_template: mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi
    image_templates:
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi-amd64
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi-arm64
  - name_template: mondoo/{{ .ProjectName }}:edge-latest-ubi
    image_templates:
      - mondoo/{{ .ProjectName }}:edge-latest-ubi-amd64
      - mondoo/{{ .ProjectName }}:edge-latest-ubi-arm64
    # Standard containers
  - name_template: mondoo/{{ .ProjectName }}:edge-{{ .Version }}
    image_templates:
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-amd64
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-arm64v8
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-armv6
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-armv7
  - name_template: mondoo/{{ .ProjectName }}:edge-latest
    image_templates:
      - mondoo/{{ .ProjectName }}:edge-latest-amd64
      - mondoo/{{ .ProjectName }}:edge-latest-arm64v8
      - mondoo/{{ .ProjectName }}:edge-latest-armv6
      - mondoo/{{ .ProjectName }}:edge-latest-armv7
  # Rootless
    # UBI containers
  - name_template: mondoo/{{ .ProjectName }}:{{ .Version }}-ubi-rootless
    image_templates:
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi-amd64-rootless
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-ubi-arm64-rootless
  - name_template: mondoo/{{ .ProjectName }}:edge-latest-ubi-rootless
    image_templates:
      - mondoo/{{ .ProjectName }}:edge-latest-ubi-amd64-rootless
      - mondoo/{{ .ProjectName }}:edge-latest-ubi-arm64-rootless
    # Standard containers
  - name_template: mondoo/{{ .ProjectName }}:edge-{{ .Version }}-rootless
    image_templates:
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-amd64-rootless
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-arm64v8-rootless
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-armv6-rootless
      - mondoo/{{ .ProjectName }}:edge-{{ .Version }}-armv7-rootless
  - name_template: mondoo/{{ .ProjectName }}:edge-latest-rootless
    image_templates:
      - mondoo/{{ .ProjectName }}:edge-latest-amd64-rootless
      - mondoo/{{ .ProjectName }}:edge-latest-arm64v8-rootless
      - mondoo/{{ .ProjectName }}:edge-latest-armv6-rootless
      - mondoo/{{ .ProjectName }}:edge-latest-armv7-rootless
