# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# See https://golangci-lint.run/usage/configuration/ for configuration options
run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.lr\\.go$"

linters:
  disable-all: true
  enable:
    - gofmt
    - depguard
# deactivated for now since its slow in github actions
#    - govet

linters-settings:
  gofmt:
    simplify: false

  govet:
    # enable or disable analyzers by name
    # run `go tool vet help` to see all analyzers
    enable:
      - structtag
      - lostcancel
    disable-all: true

  depguard:
    rules:
      denied-packages:
        deny:
          - pkg: "gotest.tools"
            desc: Should be replaced with "github.com/stretchr/testify/assert"
          - pkg: "github.com/mitchellh/mapstructure"
            desc: "no longer maintained; use github.com/go-viper/mapstructure/v2 v2.2.1 instead"
