# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - depguard
  settings:
    depguard:
      rules:
        denied-packages:
          deny:
            - pkg: gotest.tools
              desc: Should be replaced with "github.com/stretchr/testify/assert"
            - pkg: github.com/tj/assert
              desc: Should be replaced with "github.com/stretchr/testify/assert"
            - pkg: github.com/mitchellh/mapstructure
              desc: no longer maintained; use github.com/go-viper/mapstructure/v2 v2.2.1 instead
        prevent-viper-in-internal-packages:
          files:
            - $all
            - '!$test'
            - '!**/cmd/**'
            - '!**/cli/**'
            - '!**/local_scanner.go'
          deny:
            - pkg: github.com/spf13/viper
              desc: viper should only be used in CLI packages (under cmd/ or cli/)
    govet:
      enable:
        - structtag
        - lostcancel
      disable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go$
      - .*\.lr\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*\.lr\.go$
      - third_party$
      - builtin$
      - examples$
