# See https://golangci-lint.run/usage/configuration/ for configuration options
run:
  timeout: 5m
  skip-dirs:
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.lr\\.go$"
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
# deactivated for now since its slow in github actions
#    - govet

linters-settings:
  gofmt:
    simplify: false

  govet:
    # enable or disable analyzers by name
    # run `go tool vet help` to see all analyzers
    enable:
      - structtag
      - lostcancel
    disable-all: true
