// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestModelNotFoundError(t *testing.T) {
	err := modelNotFoundError("llama3.1:latest")

	assert.True(t, errors.Is(err, errModelNotFound),
		"a missing model must stay classifiable, so ollama.runningModel.model reports null instead of failing")
	assert.Contains(t, err.Error(), `"llama3.1:latest"`, "the message still names the model")

	assert.False(t, errors.Is(fmt.Errorf("dial tcp 127.0.0.1:11434: connect: connection refused"), errModelNotFound),
		"a transport failure must never be degraded to a missing model")
}

func TestModelRef(t *testing.T) {
	t.Run("short name inherits the ollama defaults", func(t *testing.T) {
		registry, namespace, repository, tag := modelRef("llama3.1:latest")
		assert.Equal(t, "registry.ollama.ai", registry)
		assert.Equal(t, "library", namespace)
		assert.Equal(t, "llama3.1", repository)
		assert.Equal(t, "latest", tag)
	})

	t.Run("bare name gets the default tag", func(t *testing.T) {
		_, _, repository, tag := modelRef("llama3.1")
		assert.Equal(t, "llama3.1", repository)
		assert.Equal(t, "latest", tag, "an untagged name resolves to latest")
	})

	t.Run("third-party registry is reported as-is", func(t *testing.T) {
		registry, namespace, repository, tag := modelRef("registry.example.com/team/secret-model:v1")
		assert.Equal(t, "registry.example.com", registry, "a non-default registry must not be reported as registry.ollama.ai")
		assert.Equal(t, "team", namespace)
		assert.Equal(t, "secret-model", repository)
		assert.Equal(t, "v1", tag)
	})

	t.Run("unparseable name claims no provenance", func(t *testing.T) {
		registry, namespace, repository, tag := modelRef("")
		assert.Empty(t, registry, "an unreadable name must not report the default registry")
		assert.Empty(t, namespace)
		assert.Empty(t, repository)
		assert.Empty(t, tag)
	})
}

func TestModelfileAdapters(t *testing.T) {
	t.Run("no adapters", func(t *testing.T) {
		assert.Empty(t, modelfileAdapters("FROM llama3.1:latest\nPARAMETER num_ctx 4096\n"))
	})

	t.Run("empty modelfile", func(t *testing.T) {
		assert.Empty(t, modelfileAdapters(""))
	})

	t.Run("commented instructions are ignored", func(t *testing.T) {
		// `ollama show --modelfile` emits a commented FROM header; a commented
		// ADAPTER must not be reported as applied.
		modelfile := "# Modelfile generated by \"ollama show\"\n# ADAPTER /tmp/not-applied.gguf\nFROM /root/.ollama/blobs/sha256-abc\n"
		assert.Empty(t, modelfileAdapters(modelfile))
	})

	t.Run("collects every adapter", func(t *testing.T) {
		modelfile := "FROM llama3.1:latest\nADAPTER /opt/lora/first.gguf\nadapter /opt/lora/second.gguf\n"
		assert.Equal(t,
			[]string{"/opt/lora/first.gguf", "/opt/lora/second.gguf"},
			modelfileAdapters(modelfile),
			"the instruction name is case-insensitive")
	})

	t.Run("tab separator and quoted target", func(t *testing.T) {
		modelfile := "ADAPTER\t\"/opt/lora/path with spaces.gguf\"\n"
		assert.Equal(t, []string{"/opt/lora/path with spaces.gguf"}, modelfileAdapters(modelfile))
	})

	t.Run("instruction with no target is skipped", func(t *testing.T) {
		assert.Empty(t, modelfileAdapters("ADAPTER\nADAPTER   \n"))
	})

	t.Run("similarly named instructions are not matched", func(t *testing.T) {
		assert.Empty(t, modelfileAdapters("ADAPTERS /opt/lora/first.gguf\n"))
	})
}

func TestGetString(t *testing.T) {
	m := map[string]any{
		"general.architecture": "llama",
		"general.parameter":    float64(42),
		"general.nil":          nil,
	}
	assert.Equal(t, "llama", getString(m, "general.architecture"))
	assert.Equal(t, "", getString(m, "missing"), "missing key returns empty string")
	assert.Equal(t, "", getString(m, "general.parameter"), "non-string value returns empty string")
	assert.Equal(t, "", getString(m, "general.nil"), "nil value returns empty string")
}

func TestGetInt(t *testing.T) {
	// JSON numbers decode into map[string]any as float64, which is the real
	// wire type from the ollama client; int64 is covered for completeness.
	m := map[string]any{
		"float": float64(8030261248),
		"int64": int64(4096),
		"str":   "128",
		"nil":   nil,
	}
	assert.Equal(t, int64(8030261248), getInt(m, "float"), "large float64 preserved without precision loss")
	assert.Equal(t, int64(4096), getInt(m, "int64"))
	assert.Equal(t, int64(0), getInt(m, "missing"), "missing key returns zero")
	assert.Equal(t, int64(0), getInt(m, "str"), "non-numeric value returns zero")
	assert.Equal(t, int64(0), getInt(m, "nil"), "nil value returns zero")
}

func TestGetArchInt(t *testing.T) {
	m := map[string]any{
		"llama.context_length":       float64(131072),
		"llama.attention.head_count": float64(32),
		"qwen2.embedding_length":     float64(3584),
	}
	assert.Equal(t, int64(131072), getArchInt(m, "llama", "context_length"))
	assert.Equal(t, int64(32), getArchInt(m, "llama", "attention.head_count"))
	assert.Equal(t, int64(3584), getArchInt(m, "qwen2", "embedding_length"))
	assert.Equal(t, int64(0), getArchInt(m, "llama", "embedding_length"), "wrong arch prefix returns zero")
	assert.Equal(t, int64(0), getArchInt(m, "", "context_length"), "empty arch returns zero, not a panic")
}

func TestGetStringSlice(t *testing.T) {
	m := map[string]any{
		"general.languages": []any{"en", "de", "fr"},
		"mixed":             []any{"en", float64(1), "de"},
		"scalar":            "en",
		"nil":               nil,
		"empty":             []any{},
	}
	assert.Equal(t, []interface{}{"en", "de", "fr"}, getStringSlice(m, "general.languages"))
	assert.Equal(t, []interface{}{"en", "de"}, getStringSlice(m, "mixed"), "non-string elements are skipped")
	assert.Equal(t, []interface{}{}, getStringSlice(m, "scalar"), "scalar (non-array) value yields empty slice")
	assert.Equal(t, []interface{}{}, getStringSlice(m, "missing"), "missing key yields empty slice")
	assert.Equal(t, []interface{}{}, getStringSlice(m, "nil"), "nil value yields empty slice")
	assert.Equal(t, []interface{}{}, getStringSlice(m, "empty"))
}

// A Modelfile is mostly PARAMETER and TEMPLATE lines that the adapter scan
// never looks at, so splitting it into a slice of every line allocates one
// string header per line to find a handful of matches. Walking it with an
// iterator drops that slice: the scan allocates only the result.
//
// This gate is an allocation count, which is exact and does not depend on how
// busy the machine is. It does not express "the cost must not grow with the
// file" on its own -- both forms hold their count steady as the file grows --
// but any implementation that materializes the lines again pays for that slice
// and trips the ceiling.
func TestModelfileAdaptersDoesNotMaterializeLines(t *testing.T) {
	var sb strings.Builder
	sb.WriteString("# Modelfile generated by \"ollama show\"\n")
	sb.WriteString("FROM /root/.ollama/models/blobs/sha256-abcdef0123456789\n")
	for i := 0; i < 400; i++ {
		sb.WriteString("PARAMETER stop \"<|eot_id|>" + strconv.Itoa(i) + "\"\n")
	}
	sb.WriteString("ADAPTER /opt/lora/adapter.gguf\n")
	modelfile := sb.String()

	allocs := testing.AllocsPerRun(200, func() {
		sink = modelfileAdapters(modelfile)
	})

	assert.Equal(t, []string{"/opt/lora/adapter.gguf"}, sink, "the scan still finds the adapter")
	assert.LessOrEqual(t, allocs, 1.0,
		"modelfileAdapters made %.0f allocations on a 400-line Modelfile; only the result slice may allocate", allocs)
}

var sink []string
