// Code generated by protoc-gen-rangerrpc version DO NOT EDIT.
// source: health.proto

package health

import (
	"context"
	"errors"
	"net/http"
	"net/url"
	"strings"

	ranger "go.mondoo.com/ranger-rpc"
	"go.mondoo.com/ranger-rpc/metadata"
	jsonpb "google.golang.org/protobuf/encoding/protojson"
	pb "google.golang.org/protobuf/proto"
)

// service interface definition

type Health interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// client implementation

type HealthClient struct {
	ranger.Client
	httpclient ranger.HTTPClient
	prefix     string
}

func NewHealthClient(addr string, client ranger.HTTPClient, plugins ...ranger.ClientPlugin) (*HealthClient, error) {
	base, err := url.Parse(ranger.SanitizeUrl(addr))
	if err != nil {
		return nil, err
	}

	u, err := url.Parse("./Health")
	if err != nil {
		return nil, err
	}

	serviceClient := &HealthClient{
		httpclient: client,
		prefix:     base.ResolveReference(u).String(),
	}
	serviceClient.AddPlugins(plugins...)
	return serviceClient, nil
}
func (c *HealthClient) Check(ctx context.Context, in *HealthCheckRequest) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.DoClientRequest(ctx, c.httpclient, strings.Join([]string{c.prefix, "/Check"}, ""), in, out)
	return out, err
}

// server implementation

type HealthServerOption func(s *HealthServer)

func WithUnknownFieldsForHealthServer() HealthServerOption {
	return func(s *HealthServer) {
		s.allowUnknownFields = true
	}
}

func NewHealthServer(handler Health, opts ...HealthServerOption) http.Handler {
	srv := &HealthServer{
		handler: handler,
	}

	for i := range opts {
		opts[i](srv)
	}

	service := ranger.Service{
		Name: "Health",
		Methods: map[string]ranger.Method{
			"Check": srv.Check,
		},
	}
	return ranger.NewRPCServer(&service)
}

type HealthServer struct {
	handler            Health
	allowUnknownFields bool
}

func (p *HealthServer) Check(ctx context.Context, reqBytes *[]byte) (pb.Message, error) {
	var req HealthCheckRequest
	var err error

	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.New("could not access header")
	}

	switch md.First("Content-Type") {
	case "application/protobuf", "application/octet-stream", "application/grpc+proto":
		err = pb.Unmarshal(*reqBytes, &req)
	default:
		// handle case of empty object
		if len(*reqBytes) > 0 {
			err = jsonpb.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(*reqBytes, &req)
		}
	}

	if err != nil {
		return nil, err
	}
	return p.handler.Check(ctx, &req)
}
