// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"
	"time"

	"go.mondoo.com/mql/v13/llx"
	"go.mondoo.com/mql/v13/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/v13/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourceOpenai                      string = "openai"
	ResourceOpenaiModel                 string = "openai.model"
	ResourceOpenaiFile                  string = "openai.file"
	ResourceOpenaiFineTuningJob         string = "openai.fineTuningJob"
	ResourceOpenaiVectorStore           string = "openai.vectorStore"
	ResourceOpenaiProject               string = "openai.project"
	ResourceOpenaiProjectApiKey         string = "openai.project.apiKey"
	ResourceOpenaiProjectServiceAccount string = "openai.project.serviceAccount"
	ResourceOpenaiOrganizationUser      string = "openai.organizationUser"
	ResourceOpenaiInvite                string = "openai.invite"
	ResourceOpenaiAuditLog              string = "openai.auditLog"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"openai": {
			// to override args, implement: initOpenai(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenai,
		},
		"openai.model": {
			// to override args, implement: initOpenaiModel(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiModel,
		},
		"openai.file": {
			Init:   initOpenaiFile,
			Create: createOpenaiFile,
		},
		"openai.fineTuningJob": {
			// to override args, implement: initOpenaiFineTuningJob(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiFineTuningJob,
		},
		"openai.vectorStore": {
			// to override args, implement: initOpenaiVectorStore(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiVectorStore,
		},
		"openai.project": {
			// to override args, implement: initOpenaiProject(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiProject,
		},
		"openai.project.apiKey": {
			// to override args, implement: initOpenaiProjectApiKey(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiProjectApiKey,
		},
		"openai.project.serviceAccount": {
			// to override args, implement: initOpenaiProjectServiceAccount(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiProjectServiceAccount,
		},
		"openai.organizationUser": {
			// to override args, implement: initOpenaiOrganizationUser(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiOrganizationUser,
		},
		"openai.invite": {
			// to override args, implement: initOpenaiInvite(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiInvite,
		},
		"openai.auditLog": {
			// to override args, implement: initOpenaiAuditLog(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createOpenaiAuditLog,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"openai.organization": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetOrganization()).ToDataRes(types.String)
	},
	"openai.projectId": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetProjectId()).ToDataRes(types.String)
	},
	"openai.models": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetModels()).ToDataRes(types.Array(types.Resource("openai.model")))
	},
	"openai.files": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetFiles()).ToDataRes(types.Array(types.Resource("openai.file")))
	},
	"openai.fineTuningJobs": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetFineTuningJobs()).ToDataRes(types.Array(types.Resource("openai.fineTuningJob")))
	},
	"openai.vectorStores": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetVectorStores()).ToDataRes(types.Array(types.Resource("openai.vectorStore")))
	},
	"openai.projects": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetProjects()).ToDataRes(types.Array(types.Resource("openai.project")))
	},
	"openai.users": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetUsers()).ToDataRes(types.Array(types.Resource("openai.organizationUser")))
	},
	"openai.invites": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetInvites()).ToDataRes(types.Array(types.Resource("openai.invite")))
	},
	"openai.auditLogs": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenai).GetAuditLogs()).ToDataRes(types.Array(types.Resource("openai.auditLog")))
	},
	"openai.model.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiModel).GetId()).ToDataRes(types.String)
	},
	"openai.model.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiModel).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.model.ownedBy": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiModel).GetOwnedBy()).ToDataRes(types.String)
	},
	"openai.model.isFineTuned": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiModel).GetIsFineTuned()).ToDataRes(types.Bool)
	},
	"openai.model.baseModel": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiModel).GetBaseModel()).ToDataRes(types.String)
	},
	"openai.file.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFile).GetId()).ToDataRes(types.String)
	},
	"openai.file.filename": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFile).GetFilename()).ToDataRes(types.String)
	},
	"openai.file.bytes": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFile).GetBytes()).ToDataRes(types.Int)
	},
	"openai.file.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFile).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.file.purpose": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFile).GetPurpose()).ToDataRes(types.String)
	},
	"openai.file.status": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFile).GetStatus()).ToDataRes(types.String)
	},
	"openai.fineTuningJob.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetId()).ToDataRes(types.String)
	},
	"openai.fineTuningJob.model": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetModel()).ToDataRes(types.String)
	},
	"openai.fineTuningJob.status": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetStatus()).ToDataRes(types.String)
	},
	"openai.fineTuningJob.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.fineTuningJob.finishedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetFinishedAt()).ToDataRes(types.Time)
	},
	"openai.fineTuningJob.fineTunedModel": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetFineTunedModel()).ToDataRes(types.String)
	},
	"openai.fineTuningJob.trainingFile": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetTrainingFile()).ToDataRes(types.Resource("openai.file"))
	},
	"openai.fineTuningJob.validationFile": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetValidationFile()).ToDataRes(types.Resource("openai.file"))
	},
	"openai.fineTuningJob.trainedTokens": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetTrainedTokens()).ToDataRes(types.Int)
	},
	"openai.fineTuningJob.seed": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetSeed()).ToDataRes(types.Int)
	},
	"openai.fineTuningJob.organizationId": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetOrganizationId()).ToDataRes(types.String)
	},
	"openai.fineTuningJob.hyperparameters": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetHyperparameters()).ToDataRes(types.Dict)
	},
	"openai.fineTuningJob.error": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiFineTuningJob).GetError()).ToDataRes(types.Dict)
	},
	"openai.vectorStore.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetId()).ToDataRes(types.String)
	},
	"openai.vectorStore.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetName()).ToDataRes(types.String)
	},
	"openai.vectorStore.status": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetStatus()).ToDataRes(types.String)
	},
	"openai.vectorStore.usageBytes": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetUsageBytes()).ToDataRes(types.Int)
	},
	"openai.vectorStore.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.vectorStore.lastActiveAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetLastActiveAt()).ToDataRes(types.Time)
	},
	"openai.vectorStore.fileCounts": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetFileCounts()).ToDataRes(types.Dict)
	},
	"openai.vectorStore.expiresAfter": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetExpiresAfter()).ToDataRes(types.Dict)
	},
	"openai.vectorStore.expiresAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetExpiresAt()).ToDataRes(types.Time)
	},
	"openai.vectorStore.metadata": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiVectorStore).GetMetadata()).ToDataRes(types.Dict)
	},
	"openai.project.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProject).GetId()).ToDataRes(types.String)
	},
	"openai.project.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProject).GetName()).ToDataRes(types.String)
	},
	"openai.project.status": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProject).GetStatus()).ToDataRes(types.String)
	},
	"openai.project.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProject).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.project.archivedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProject).GetArchivedAt()).ToDataRes(types.Time)
	},
	"openai.project.apiKeys": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProject).GetApiKeys()).ToDataRes(types.Array(types.Resource("openai.project.apiKey")))
	},
	"openai.project.serviceAccounts": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProject).GetServiceAccounts()).ToDataRes(types.Array(types.Resource("openai.project.serviceAccount")))
	},
	"openai.project.apiKey.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectApiKey).GetId()).ToDataRes(types.String)
	},
	"openai.project.apiKey.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectApiKey).GetName()).ToDataRes(types.String)
	},
	"openai.project.apiKey.redactedValue": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectApiKey).GetRedactedValue()).ToDataRes(types.String)
	},
	"openai.project.apiKey.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectApiKey).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.project.apiKey.lastUsedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectApiKey).GetLastUsedAt()).ToDataRes(types.Time)
	},
	"openai.project.apiKey.ownerType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectApiKey).GetOwnerType()).ToDataRes(types.String)
	},
	"openai.project.apiKey.ownerName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectApiKey).GetOwnerName()).ToDataRes(types.String)
	},
	"openai.project.apiKey.ownerId": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectApiKey).GetOwnerId()).ToDataRes(types.String)
	},
	"openai.project.serviceAccount.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectServiceAccount).GetId()).ToDataRes(types.String)
	},
	"openai.project.serviceAccount.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectServiceAccount).GetName()).ToDataRes(types.String)
	},
	"openai.project.serviceAccount.role": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectServiceAccount).GetRole()).ToDataRes(types.String)
	},
	"openai.project.serviceAccount.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiProjectServiceAccount).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.organizationUser.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetId()).ToDataRes(types.String)
	},
	"openai.organizationUser.email": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetEmail()).ToDataRes(types.String)
	},
	"openai.organizationUser.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetName()).ToDataRes(types.String)
	},
	"openai.organizationUser.role": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetRole()).ToDataRes(types.String)
	},
	"openai.organizationUser.isDefault": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetIsDefault()).ToDataRes(types.Bool)
	},
	"openai.organizationUser.isScimManaged": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetIsScimManaged()).ToDataRes(types.Bool)
	},
	"openai.organizationUser.isServiceAccount": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetIsServiceAccount()).ToDataRes(types.Bool)
	},
	"openai.organizationUser.addedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetAddedAt()).ToDataRes(types.Time)
	},
	"openai.organizationUser.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.organizationUser.apiKeyLastUsedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiOrganizationUser).GetApiKeyLastUsedAt()).ToDataRes(types.Time)
	},
	"openai.invite.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiInvite).GetId()).ToDataRes(types.String)
	},
	"openai.invite.email": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiInvite).GetEmail()).ToDataRes(types.String)
	},
	"openai.invite.role": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiInvite).GetRole()).ToDataRes(types.String)
	},
	"openai.invite.status": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiInvite).GetStatus()).ToDataRes(types.String)
	},
	"openai.invite.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiInvite).GetCreatedAt()).ToDataRes(types.Time)
	},
	"openai.invite.acceptedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiInvite).GetAcceptedAt()).ToDataRes(types.Time)
	},
	"openai.invite.expiresAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiInvite).GetExpiresAt()).ToDataRes(types.Time)
	},
	"openai.auditLog.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiAuditLog).GetId()).ToDataRes(types.String)
	},
	"openai.auditLog.type": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiAuditLog).GetType()).ToDataRes(types.String)
	},
	"openai.auditLog.effectiveAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiAuditLog).GetEffectiveAt()).ToDataRes(types.Time)
	},
	"openai.auditLog.actorType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiAuditLog).GetActorType()).ToDataRes(types.String)
	},
	"openai.auditLog.actorId": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlOpenaiAuditLog).GetActorId()).ToDataRes(types.String)
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"openai.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).__id, ok = v.Value.(string)
		return
	},
	"openai.organization": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).Organization, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.projectId": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).ProjectId, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.models": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).Models, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.files": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).Files, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.fineTuningJobs": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).FineTuningJobs, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.vectorStores": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).VectorStores, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.projects": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).Projects, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.users": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).Users, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.invites": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).Invites, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.auditLogs": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenai).AuditLogs, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.model.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiModel).__id, ok = v.Value.(string)
		return
	},
	"openai.model.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiModel).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.model.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiModel).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.model.ownedBy": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiModel).OwnedBy, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.model.isFineTuned": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiModel).IsFineTuned, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"openai.model.baseModel": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiModel).BaseModel, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.file.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFile).__id, ok = v.Value.(string)
		return
	},
	"openai.file.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFile).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.file.filename": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFile).Filename, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.file.bytes": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFile).Bytes, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"openai.file.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFile).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.file.purpose": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFile).Purpose, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.file.status": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFile).Status, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).__id, ok = v.Value.(string)
		return
	},
	"openai.fineTuningJob.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.model": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).Model, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.status": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).Status, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.finishedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).FinishedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.fineTunedModel": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).FineTunedModel, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.trainingFile": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).TrainingFile, ok = plugin.RawToTValue[*mqlOpenaiFile](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.validationFile": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).ValidationFile, ok = plugin.RawToTValue[*mqlOpenaiFile](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.trainedTokens": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).TrainedTokens, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.seed": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).Seed, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.organizationId": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).OrganizationId, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.hyperparameters": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).Hyperparameters, ok = plugin.RawToTValue[any](v.Value, v.Error)
		return
	},
	"openai.fineTuningJob.error": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiFineTuningJob).Error, ok = plugin.RawToTValue[any](v.Value, v.Error)
		return
	},
	"openai.vectorStore.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).__id, ok = v.Value.(string)
		return
	},
	"openai.vectorStore.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.vectorStore.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.vectorStore.status": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).Status, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.vectorStore.usageBytes": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).UsageBytes, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"openai.vectorStore.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.vectorStore.lastActiveAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).LastActiveAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.vectorStore.fileCounts": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).FileCounts, ok = plugin.RawToTValue[any](v.Value, v.Error)
		return
	},
	"openai.vectorStore.expiresAfter": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).ExpiresAfter, ok = plugin.RawToTValue[any](v.Value, v.Error)
		return
	},
	"openai.vectorStore.expiresAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).ExpiresAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.vectorStore.metadata": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiVectorStore).Metadata, ok = plugin.RawToTValue[any](v.Value, v.Error)
		return
	},
	"openai.project.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProject).__id, ok = v.Value.(string)
		return
	},
	"openai.project.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProject).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProject).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.status": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProject).Status, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProject).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.project.archivedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProject).ArchivedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.project.apiKeys": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProject).ApiKeys, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.project.serviceAccounts": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProject).ServiceAccounts, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"openai.project.apiKey.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).__id, ok = v.Value.(string)
		return
	},
	"openai.project.apiKey.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.apiKey.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.apiKey.redactedValue": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).RedactedValue, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.apiKey.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.project.apiKey.lastUsedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).LastUsedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.project.apiKey.ownerType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).OwnerType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.apiKey.ownerName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).OwnerName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.apiKey.ownerId": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectApiKey).OwnerId, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.serviceAccount.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectServiceAccount).__id, ok = v.Value.(string)
		return
	},
	"openai.project.serviceAccount.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectServiceAccount).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.serviceAccount.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectServiceAccount).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.serviceAccount.role": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectServiceAccount).Role, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.project.serviceAccount.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiProjectServiceAccount).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.organizationUser.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).__id, ok = v.Value.(string)
		return
	},
	"openai.organizationUser.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.organizationUser.email": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).Email, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.organizationUser.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.organizationUser.role": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).Role, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.organizationUser.isDefault": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).IsDefault, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"openai.organizationUser.isScimManaged": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).IsScimManaged, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"openai.organizationUser.isServiceAccount": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).IsServiceAccount, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"openai.organizationUser.addedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).AddedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.organizationUser.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.organizationUser.apiKeyLastUsedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiOrganizationUser).ApiKeyLastUsedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.invite.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiInvite).__id, ok = v.Value.(string)
		return
	},
	"openai.invite.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiInvite).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.invite.email": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiInvite).Email, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.invite.role": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiInvite).Role, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.invite.status": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiInvite).Status, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.invite.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiInvite).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.invite.acceptedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiInvite).AcceptedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.invite.expiresAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiInvite).ExpiresAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.auditLog.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiAuditLog).__id, ok = v.Value.(string)
		return
	},
	"openai.auditLog.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiAuditLog).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.auditLog.type": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiAuditLog).Type, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.auditLog.effectiveAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiAuditLog).EffectiveAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"openai.auditLog.actorType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiAuditLog).ActorType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"openai.auditLog.actorId": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlOpenaiAuditLog).ActorId, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[openai] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[openai] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlOpenai for the openai resource
type mqlOpenai struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiInternal it will be used here
	Organization   plugin.TValue[string]
	ProjectId      plugin.TValue[string]
	Models         plugin.TValue[[]any]
	Files          plugin.TValue[[]any]
	FineTuningJobs plugin.TValue[[]any]
	VectorStores   plugin.TValue[[]any]
	Projects       plugin.TValue[[]any]
	Users          plugin.TValue[[]any]
	Invites        plugin.TValue[[]any]
	AuditLogs      plugin.TValue[[]any]
}

// createOpenai creates a new instance of this resource
func createOpenai(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenai{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenai) MqlName() string {
	return "openai"
}

func (c *mqlOpenai) MqlID() string {
	return c.__id
}

func (c *mqlOpenai) GetOrganization() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.Organization, func() (string, error) {
		return c.organization()
	})
}

func (c *mqlOpenai) GetProjectId() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.ProjectId, func() (string, error) {
		return c.projectId()
	})
}

func (c *mqlOpenai) GetModels() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Models, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai", c.__id, "models")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.models()
	})
}

func (c *mqlOpenai) GetFiles() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Files, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai", c.__id, "files")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.files()
	})
}

func (c *mqlOpenai) GetFineTuningJobs() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.FineTuningJobs, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai", c.__id, "fineTuningJobs")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.fineTuningJobs()
	})
}

func (c *mqlOpenai) GetVectorStores() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.VectorStores, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai", c.__id, "vectorStores")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.vectorStores()
	})
}

func (c *mqlOpenai) GetProjects() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Projects, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai", c.__id, "projects")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.projects()
	})
}

func (c *mqlOpenai) GetUsers() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Users, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai", c.__id, "users")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.users()
	})
}

func (c *mqlOpenai) GetInvites() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Invites, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai", c.__id, "invites")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.invites()
	})
}

func (c *mqlOpenai) GetAuditLogs() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.AuditLogs, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai", c.__id, "auditLogs")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.auditLogs()
	})
}

// mqlOpenaiModel for the openai.model resource
type mqlOpenaiModel struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiModelInternal it will be used here
	Id          plugin.TValue[string]
	CreatedAt   plugin.TValue[*time.Time]
	OwnedBy     plugin.TValue[string]
	IsFineTuned plugin.TValue[bool]
	BaseModel   plugin.TValue[string]
}

// createOpenaiModel creates a new instance of this resource
func createOpenaiModel(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiModel{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.model", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiModel) MqlName() string {
	return "openai.model"
}

func (c *mqlOpenaiModel) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiModel) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiModel) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlOpenaiModel) GetOwnedBy() *plugin.TValue[string] {
	return &c.OwnedBy
}

func (c *mqlOpenaiModel) GetIsFineTuned() *plugin.TValue[bool] {
	return plugin.GetOrCompute[bool](&c.IsFineTuned, func() (bool, error) {
		return c.isFineTuned()
	})
}

func (c *mqlOpenaiModel) GetBaseModel() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.BaseModel, func() (string, error) {
		return c.baseModel()
	})
}

// mqlOpenaiFile for the openai.file resource
type mqlOpenaiFile struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiFileInternal it will be used here
	Id        plugin.TValue[string]
	Filename  plugin.TValue[string]
	Bytes     plugin.TValue[int64]
	CreatedAt plugin.TValue[*time.Time]
	Purpose   plugin.TValue[string]
	Status    plugin.TValue[string]
}

// createOpenaiFile creates a new instance of this resource
func createOpenaiFile(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiFile{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.file", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiFile) MqlName() string {
	return "openai.file"
}

func (c *mqlOpenaiFile) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiFile) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiFile) GetFilename() *plugin.TValue[string] {
	return &c.Filename
}

func (c *mqlOpenaiFile) GetBytes() *plugin.TValue[int64] {
	return &c.Bytes
}

func (c *mqlOpenaiFile) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlOpenaiFile) GetPurpose() *plugin.TValue[string] {
	return &c.Purpose
}

func (c *mqlOpenaiFile) GetStatus() *plugin.TValue[string] {
	return &c.Status
}

// mqlOpenaiFineTuningJob for the openai.fineTuningJob resource
type mqlOpenaiFineTuningJob struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlOpenaiFineTuningJobInternal
	Id              plugin.TValue[string]
	Model           plugin.TValue[string]
	Status          plugin.TValue[string]
	CreatedAt       plugin.TValue[*time.Time]
	FinishedAt      plugin.TValue[*time.Time]
	FineTunedModel  plugin.TValue[string]
	TrainingFile    plugin.TValue[*mqlOpenaiFile]
	ValidationFile  plugin.TValue[*mqlOpenaiFile]
	TrainedTokens   plugin.TValue[int64]
	Seed            plugin.TValue[int64]
	OrganizationId  plugin.TValue[string]
	Hyperparameters plugin.TValue[any]
	Error           plugin.TValue[any]
}

// createOpenaiFineTuningJob creates a new instance of this resource
func createOpenaiFineTuningJob(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiFineTuningJob{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.fineTuningJob", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiFineTuningJob) MqlName() string {
	return "openai.fineTuningJob"
}

func (c *mqlOpenaiFineTuningJob) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiFineTuningJob) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiFineTuningJob) GetModel() *plugin.TValue[string] {
	return &c.Model
}

func (c *mqlOpenaiFineTuningJob) GetStatus() *plugin.TValue[string] {
	return &c.Status
}

func (c *mqlOpenaiFineTuningJob) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlOpenaiFineTuningJob) GetFinishedAt() *plugin.TValue[*time.Time] {
	return &c.FinishedAt
}

func (c *mqlOpenaiFineTuningJob) GetFineTunedModel() *plugin.TValue[string] {
	return &c.FineTunedModel
}

func (c *mqlOpenaiFineTuningJob) GetTrainingFile() *plugin.TValue[*mqlOpenaiFile] {
	return plugin.GetOrCompute[*mqlOpenaiFile](&c.TrainingFile, func() (*mqlOpenaiFile, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai.fineTuningJob", c.__id, "trainingFile")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlOpenaiFile), nil
			}
		}

		return c.trainingFile()
	})
}

func (c *mqlOpenaiFineTuningJob) GetValidationFile() *plugin.TValue[*mqlOpenaiFile] {
	return plugin.GetOrCompute[*mqlOpenaiFile](&c.ValidationFile, func() (*mqlOpenaiFile, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai.fineTuningJob", c.__id, "validationFile")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlOpenaiFile), nil
			}
		}

		return c.validationFile()
	})
}

func (c *mqlOpenaiFineTuningJob) GetTrainedTokens() *plugin.TValue[int64] {
	return &c.TrainedTokens
}

func (c *mqlOpenaiFineTuningJob) GetSeed() *plugin.TValue[int64] {
	return &c.Seed
}

func (c *mqlOpenaiFineTuningJob) GetOrganizationId() *plugin.TValue[string] {
	return &c.OrganizationId
}

func (c *mqlOpenaiFineTuningJob) GetHyperparameters() *plugin.TValue[any] {
	return &c.Hyperparameters
}

func (c *mqlOpenaiFineTuningJob) GetError() *plugin.TValue[any] {
	return &c.Error
}

// mqlOpenaiVectorStore for the openai.vectorStore resource
type mqlOpenaiVectorStore struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiVectorStoreInternal it will be used here
	Id           plugin.TValue[string]
	Name         plugin.TValue[string]
	Status       plugin.TValue[string]
	UsageBytes   plugin.TValue[int64]
	CreatedAt    plugin.TValue[*time.Time]
	LastActiveAt plugin.TValue[*time.Time]
	FileCounts   plugin.TValue[any]
	ExpiresAfter plugin.TValue[any]
	ExpiresAt    plugin.TValue[*time.Time]
	Metadata     plugin.TValue[any]
}

// createOpenaiVectorStore creates a new instance of this resource
func createOpenaiVectorStore(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiVectorStore{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.vectorStore", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiVectorStore) MqlName() string {
	return "openai.vectorStore"
}

func (c *mqlOpenaiVectorStore) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiVectorStore) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiVectorStore) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlOpenaiVectorStore) GetStatus() *plugin.TValue[string] {
	return &c.Status
}

func (c *mqlOpenaiVectorStore) GetUsageBytes() *plugin.TValue[int64] {
	return &c.UsageBytes
}

func (c *mqlOpenaiVectorStore) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlOpenaiVectorStore) GetLastActiveAt() *plugin.TValue[*time.Time] {
	return &c.LastActiveAt
}

func (c *mqlOpenaiVectorStore) GetFileCounts() *plugin.TValue[any] {
	return &c.FileCounts
}

func (c *mqlOpenaiVectorStore) GetExpiresAfter() *plugin.TValue[any] {
	return &c.ExpiresAfter
}

func (c *mqlOpenaiVectorStore) GetExpiresAt() *plugin.TValue[*time.Time] {
	return &c.ExpiresAt
}

func (c *mqlOpenaiVectorStore) GetMetadata() *plugin.TValue[any] {
	return &c.Metadata
}

// mqlOpenaiProject for the openai.project resource
type mqlOpenaiProject struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiProjectInternal it will be used here
	Id              plugin.TValue[string]
	Name            plugin.TValue[string]
	Status          plugin.TValue[string]
	CreatedAt       plugin.TValue[*time.Time]
	ArchivedAt      plugin.TValue[*time.Time]
	ApiKeys         plugin.TValue[[]any]
	ServiceAccounts plugin.TValue[[]any]
}

// createOpenaiProject creates a new instance of this resource
func createOpenaiProject(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiProject{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.project", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiProject) MqlName() string {
	return "openai.project"
}

func (c *mqlOpenaiProject) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiProject) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiProject) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlOpenaiProject) GetStatus() *plugin.TValue[string] {
	return &c.Status
}

func (c *mqlOpenaiProject) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlOpenaiProject) GetArchivedAt() *plugin.TValue[*time.Time] {
	return &c.ArchivedAt
}

func (c *mqlOpenaiProject) GetApiKeys() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.ApiKeys, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai.project", c.__id, "apiKeys")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.apiKeys()
	})
}

func (c *mqlOpenaiProject) GetServiceAccounts() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.ServiceAccounts, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("openai.project", c.__id, "serviceAccounts")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.serviceAccounts()
	})
}

// mqlOpenaiProjectApiKey for the openai.project.apiKey resource
type mqlOpenaiProjectApiKey struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiProjectApiKeyInternal it will be used here
	Id            plugin.TValue[string]
	Name          plugin.TValue[string]
	RedactedValue plugin.TValue[string]
	CreatedAt     plugin.TValue[*time.Time]
	LastUsedAt    plugin.TValue[*time.Time]
	OwnerType     plugin.TValue[string]
	OwnerName     plugin.TValue[string]
	OwnerId       plugin.TValue[string]
}

// createOpenaiProjectApiKey creates a new instance of this resource
func createOpenaiProjectApiKey(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiProjectApiKey{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.project.apiKey", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiProjectApiKey) MqlName() string {
	return "openai.project.apiKey"
}

func (c *mqlOpenaiProjectApiKey) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiProjectApiKey) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiProjectApiKey) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlOpenaiProjectApiKey) GetRedactedValue() *plugin.TValue[string] {
	return &c.RedactedValue
}

func (c *mqlOpenaiProjectApiKey) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlOpenaiProjectApiKey) GetLastUsedAt() *plugin.TValue[*time.Time] {
	return &c.LastUsedAt
}

func (c *mqlOpenaiProjectApiKey) GetOwnerType() *plugin.TValue[string] {
	return &c.OwnerType
}

func (c *mqlOpenaiProjectApiKey) GetOwnerName() *plugin.TValue[string] {
	return &c.OwnerName
}

func (c *mqlOpenaiProjectApiKey) GetOwnerId() *plugin.TValue[string] {
	return &c.OwnerId
}

// mqlOpenaiProjectServiceAccount for the openai.project.serviceAccount resource
type mqlOpenaiProjectServiceAccount struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiProjectServiceAccountInternal it will be used here
	Id        plugin.TValue[string]
	Name      plugin.TValue[string]
	Role      plugin.TValue[string]
	CreatedAt plugin.TValue[*time.Time]
}

// createOpenaiProjectServiceAccount creates a new instance of this resource
func createOpenaiProjectServiceAccount(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiProjectServiceAccount{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.project.serviceAccount", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiProjectServiceAccount) MqlName() string {
	return "openai.project.serviceAccount"
}

func (c *mqlOpenaiProjectServiceAccount) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiProjectServiceAccount) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiProjectServiceAccount) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlOpenaiProjectServiceAccount) GetRole() *plugin.TValue[string] {
	return &c.Role
}

func (c *mqlOpenaiProjectServiceAccount) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

// mqlOpenaiOrganizationUser for the openai.organizationUser resource
type mqlOpenaiOrganizationUser struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiOrganizationUserInternal it will be used here
	Id               plugin.TValue[string]
	Email            plugin.TValue[string]
	Name             plugin.TValue[string]
	Role             plugin.TValue[string]
	IsDefault        plugin.TValue[bool]
	IsScimManaged    plugin.TValue[bool]
	IsServiceAccount plugin.TValue[bool]
	AddedAt          plugin.TValue[*time.Time]
	CreatedAt        plugin.TValue[*time.Time]
	ApiKeyLastUsedAt plugin.TValue[*time.Time]
}

// createOpenaiOrganizationUser creates a new instance of this resource
func createOpenaiOrganizationUser(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiOrganizationUser{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.organizationUser", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiOrganizationUser) MqlName() string {
	return "openai.organizationUser"
}

func (c *mqlOpenaiOrganizationUser) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiOrganizationUser) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiOrganizationUser) GetEmail() *plugin.TValue[string] {
	return &c.Email
}

func (c *mqlOpenaiOrganizationUser) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlOpenaiOrganizationUser) GetRole() *plugin.TValue[string] {
	return &c.Role
}

func (c *mqlOpenaiOrganizationUser) GetIsDefault() *plugin.TValue[bool] {
	return &c.IsDefault
}

func (c *mqlOpenaiOrganizationUser) GetIsScimManaged() *plugin.TValue[bool] {
	return &c.IsScimManaged
}

func (c *mqlOpenaiOrganizationUser) GetIsServiceAccount() *plugin.TValue[bool] {
	return &c.IsServiceAccount
}

func (c *mqlOpenaiOrganizationUser) GetAddedAt() *plugin.TValue[*time.Time] {
	return &c.AddedAt
}

func (c *mqlOpenaiOrganizationUser) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlOpenaiOrganizationUser) GetApiKeyLastUsedAt() *plugin.TValue[*time.Time] {
	return &c.ApiKeyLastUsedAt
}

// mqlOpenaiInvite for the openai.invite resource
type mqlOpenaiInvite struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiInviteInternal it will be used here
	Id         plugin.TValue[string]
	Email      plugin.TValue[string]
	Role       plugin.TValue[string]
	Status     plugin.TValue[string]
	CreatedAt  plugin.TValue[*time.Time]
	AcceptedAt plugin.TValue[*time.Time]
	ExpiresAt  plugin.TValue[*time.Time]
}

// createOpenaiInvite creates a new instance of this resource
func createOpenaiInvite(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiInvite{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.invite", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiInvite) MqlName() string {
	return "openai.invite"
}

func (c *mqlOpenaiInvite) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiInvite) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiInvite) GetEmail() *plugin.TValue[string] {
	return &c.Email
}

func (c *mqlOpenaiInvite) GetRole() *plugin.TValue[string] {
	return &c.Role
}

func (c *mqlOpenaiInvite) GetStatus() *plugin.TValue[string] {
	return &c.Status
}

func (c *mqlOpenaiInvite) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlOpenaiInvite) GetAcceptedAt() *plugin.TValue[*time.Time] {
	return &c.AcceptedAt
}

func (c *mqlOpenaiInvite) GetExpiresAt() *plugin.TValue[*time.Time] {
	return &c.ExpiresAt
}

// mqlOpenaiAuditLog for the openai.auditLog resource
type mqlOpenaiAuditLog struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlOpenaiAuditLogInternal it will be used here
	Id          plugin.TValue[string]
	Type        plugin.TValue[string]
	EffectiveAt plugin.TValue[*time.Time]
	ActorType   plugin.TValue[string]
	ActorId     plugin.TValue[string]
}

// createOpenaiAuditLog creates a new instance of this resource
func createOpenaiAuditLog(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlOpenaiAuditLog{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("openai.auditLog", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlOpenaiAuditLog) MqlName() string {
	return "openai.auditLog"
}

func (c *mqlOpenaiAuditLog) MqlID() string {
	return c.__id
}

func (c *mqlOpenaiAuditLog) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlOpenaiAuditLog) GetType() *plugin.TValue[string] {
	return &c.Type
}

func (c *mqlOpenaiAuditLog) GetEffectiveAt() *plugin.TValue[*time.Time] {
	return &c.EffectiveAt
}

func (c *mqlOpenaiAuditLog) GetActorType() *plugin.TValue[string] {
	return &c.ActorType
}

func (c *mqlOpenaiAuditLog) GetActorId() *plugin.TValue[string] {
	return &c.ActorId
}
