// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"
	"time"

	"go.mondoo.com/mql/v13/llx"
	"go.mondoo.com/mql/v13/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/v13/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourcePostgres                string = "postgres"
	ResourcePostgresInstance        string = "postgres.instance"
	ResourcePostgresRole            string = "postgres.role"
	ResourcePostgresDatabase        string = "postgres.database"
	ResourcePostgresSchema          string = "postgres.schema"
	ResourcePostgresTable           string = "postgres.table"
	ResourcePostgresRlsPolicy       string = "postgres.rlsPolicy"
	ResourcePostgresFunction        string = "postgres.function"
	ResourcePostgresPrivilege       string = "postgres.privilege"
	ResourcePostgresSetting         string = "postgres.setting"
	ResourcePostgresHbaRule         string = "postgres.hbaRule"
	ResourcePostgresExtension       string = "postgres.extension"
	ResourcePostgresTablespace      string = "postgres.tablespace"
	ResourcePostgresForeignServer   string = "postgres.foreignServer"
	ResourcePostgresUserMapping     string = "postgres.userMapping"
	ResourcePostgresReplicationSlot string = "postgres.replicationSlot"
	ResourcePostgresPublication     string = "postgres.publication"
	ResourcePostgresSubscription    string = "postgres.subscription"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"postgres": {
			// to override args, implement: initPostgres(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgres,
		},
		"postgres.instance": {
			Init:   initPostgresInstance,
			Create: createPostgresInstance,
		},
		"postgres.role": {
			Init:   initPostgresRole,
			Create: createPostgresRole,
		},
		"postgres.database": {
			Init:   initPostgresDatabase,
			Create: createPostgresDatabase,
		},
		"postgres.schema": {
			// to override args, implement: initPostgresSchema(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresSchema,
		},
		"postgres.table": {
			// to override args, implement: initPostgresTable(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresTable,
		},
		"postgres.rlsPolicy": {
			// to override args, implement: initPostgresRlsPolicy(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresRlsPolicy,
		},
		"postgres.function": {
			// to override args, implement: initPostgresFunction(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresFunction,
		},
		"postgres.privilege": {
			// to override args, implement: initPostgresPrivilege(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresPrivilege,
		},
		"postgres.setting": {
			// to override args, implement: initPostgresSetting(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresSetting,
		},
		"postgres.hbaRule": {
			// to override args, implement: initPostgresHbaRule(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresHbaRule,
		},
		"postgres.extension": {
			// to override args, implement: initPostgresExtension(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresExtension,
		},
		"postgres.tablespace": {
			// to override args, implement: initPostgresTablespace(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresTablespace,
		},
		"postgres.foreignServer": {
			// to override args, implement: initPostgresForeignServer(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresForeignServer,
		},
		"postgres.userMapping": {
			// to override args, implement: initPostgresUserMapping(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresUserMapping,
		},
		"postgres.replicationSlot": {
			// to override args, implement: initPostgresReplicationSlot(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresReplicationSlot,
		},
		"postgres.publication": {
			// to override args, implement: initPostgresPublication(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresPublication,
		},
		"postgres.subscription": {
			// to override args, implement: initPostgresSubscription(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresSubscription,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"postgres.instance.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetVersion()).ToDataRes(types.String)
	},
	"postgres.instance.systemIdentifier": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetSystemIdentifier()).ToDataRes(types.String)
	},
	"postgres.instance.startTime": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetStartTime()).ToDataRes(types.Time)
	},
	"postgres.instance.inRecovery": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetInRecovery()).ToDataRes(types.Bool)
	},
	"postgres.instance.ssl": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetSsl()).ToDataRes(types.Bool)
	},
	"postgres.instance.passwordEncryption": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetPasswordEncryption()).ToDataRes(types.String)
	},
	"postgres.instance.listenAddresses": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetListenAddresses()).ToDataRes(types.String)
	},
	"postgres.instance.settings": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetSettings()).ToDataRes(types.Array(types.Resource("postgres.setting")))
	},
	"postgres.instance.roles": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetRoles()).ToDataRes(types.Array(types.Resource("postgres.role")))
	},
	"postgres.instance.databases": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetDatabases()).ToDataRes(types.Array(types.Resource("postgres.database")))
	},
	"postgres.instance.tablespaces": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetTablespaces()).ToDataRes(types.Array(types.Resource("postgres.tablespace")))
	},
	"postgres.instance.hbaRules": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetHbaRules()).ToDataRes(types.Array(types.Resource("postgres.hbaRule")))
	},
	"postgres.instance.replicationSlots": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetReplicationSlots()).ToDataRes(types.Array(types.Resource("postgres.replicationSlot")))
	},
	"postgres.instance.subscriptions": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresInstance).GetSubscriptions()).ToDataRes(types.Array(types.Resource("postgres.subscription")))
	},
	"postgres.role.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetName()).ToDataRes(types.String)
	},
	"postgres.role.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetOid()).ToDataRes(types.Int)
	},
	"postgres.role.isSuperuser": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetIsSuperuser()).ToDataRes(types.Bool)
	},
	"postgres.role.canLogin": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetCanLogin()).ToDataRes(types.Bool)
	},
	"postgres.role.createRole": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetCreateRole()).ToDataRes(types.Bool)
	},
	"postgres.role.createDb": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetCreateDb()).ToDataRes(types.Bool)
	},
	"postgres.role.isReplication": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetIsReplication()).ToDataRes(types.Bool)
	},
	"postgres.role.bypassRLS": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetBypassRLS()).ToDataRes(types.Bool)
	},
	"postgres.role.inheritsPrivileges": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetInheritsPrivileges()).ToDataRes(types.Bool)
	},
	"postgres.role.connectionLimit": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetConnectionLimit()).ToDataRes(types.Int)
	},
	"postgres.role.validUntil": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetValidUntil()).ToDataRes(types.Time)
	},
	"postgres.role.passwordType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetPasswordType()).ToDataRes(types.String)
	},
	"postgres.role.memberOf": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetMemberOf()).ToDataRes(types.Array(types.Resource("postgres.role")))
	},
	"postgres.role.members": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetMembers()).ToDataRes(types.Array(types.Resource("postgres.role")))
	},
	"postgres.role.config": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRole).GetConfig()).ToDataRes(types.Array(types.String))
	},
	"postgres.database.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetName()).ToDataRes(types.String)
	},
	"postgres.database.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetOid()).ToDataRes(types.Int)
	},
	"postgres.database.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.database.encoding": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetEncoding()).ToDataRes(types.String)
	},
	"postgres.database.collate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetCollate()).ToDataRes(types.String)
	},
	"postgres.database.ctype": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetCtype()).ToDataRes(types.String)
	},
	"postgres.database.isTemplate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetIsTemplate()).ToDataRes(types.Bool)
	},
	"postgres.database.allowConnections": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetAllowConnections()).ToDataRes(types.Bool)
	},
	"postgres.database.connectionLimit": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetConnectionLimit()).ToDataRes(types.Int)
	},
	"postgres.database.privileges": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetPrivileges()).ToDataRes(types.Array(types.Resource("postgres.privilege")))
	},
	"postgres.database.schemas": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetSchemas()).ToDataRes(types.Array(types.Resource("postgres.schema")))
	},
	"postgres.database.functions": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetFunctions()).ToDataRes(types.Array(types.Resource("postgres.function")))
	},
	"postgres.database.extensions": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetExtensions()).ToDataRes(types.Array(types.Resource("postgres.extension")))
	},
	"postgres.database.foreignServers": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetForeignServers()).ToDataRes(types.Array(types.Resource("postgres.foreignServer")))
	},
	"postgres.database.publications": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresDatabase).GetPublications()).ToDataRes(types.Array(types.Resource("postgres.publication")))
	},
	"postgres.schema.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSchema).GetName()).ToDataRes(types.String)
	},
	"postgres.schema.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSchema).GetOid()).ToDataRes(types.Int)
	},
	"postgres.schema.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSchema).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.schema.privileges": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSchema).GetPrivileges()).ToDataRes(types.Array(types.Resource("postgres.privilege")))
	},
	"postgres.schema.tables": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSchema).GetTables()).ToDataRes(types.Array(types.Resource("postgres.table")))
	},
	"postgres.table.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetName()).ToDataRes(types.String)
	},
	"postgres.table.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetOid()).ToDataRes(types.Int)
	},
	"postgres.table.schema": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetSchema()).ToDataRes(types.String)
	},
	"postgres.table.kind": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetKind()).ToDataRes(types.String)
	},
	"postgres.table.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.table.rowSecurityEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetRowSecurityEnabled()).ToDataRes(types.Bool)
	},
	"postgres.table.rowSecurityForced": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetRowSecurityForced()).ToDataRes(types.Bool)
	},
	"postgres.table.privileges": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetPrivileges()).ToDataRes(types.Array(types.Resource("postgres.privilege")))
	},
	"postgres.table.policies": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTable).GetPolicies()).ToDataRes(types.Array(types.Resource("postgres.rlsPolicy")))
	},
	"postgres.rlsPolicy.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRlsPolicy).GetName()).ToDataRes(types.String)
	},
	"postgres.rlsPolicy.command": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRlsPolicy).GetCommand()).ToDataRes(types.String)
	},
	"postgres.rlsPolicy.permissive": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRlsPolicy).GetPermissive()).ToDataRes(types.Bool)
	},
	"postgres.rlsPolicy.roles": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRlsPolicy).GetRoles()).ToDataRes(types.Array(types.String))
	},
	"postgres.rlsPolicy.usingExpression": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRlsPolicy).GetUsingExpression()).ToDataRes(types.String)
	},
	"postgres.rlsPolicy.checkExpression": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresRlsPolicy).GetCheckExpression()).ToDataRes(types.String)
	},
	"postgres.function.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresFunction).GetName()).ToDataRes(types.String)
	},
	"postgres.function.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresFunction).GetOid()).ToDataRes(types.Int)
	},
	"postgres.function.schema": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresFunction).GetSchema()).ToDataRes(types.String)
	},
	"postgres.function.language": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresFunction).GetLanguage()).ToDataRes(types.String)
	},
	"postgres.function.isSecurityDefiner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresFunction).GetIsSecurityDefiner()).ToDataRes(types.Bool)
	},
	"postgres.function.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresFunction).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.function.privileges": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresFunction).GetPrivileges()).ToDataRes(types.Array(types.Resource("postgres.privilege")))
	},
	"postgres.privilege.grantee": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPrivilege).GetGrantee()).ToDataRes(types.String)
	},
	"postgres.privilege.privilegeType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPrivilege).GetPrivilegeType()).ToDataRes(types.String)
	},
	"postgres.privilege.isGrantable": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPrivilege).GetIsGrantable()).ToDataRes(types.Bool)
	},
	"postgres.setting.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetName()).ToDataRes(types.String)
	},
	"postgres.setting.setting": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetSetting()).ToDataRes(types.String)
	},
	"postgres.setting.unit": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetUnit()).ToDataRes(types.String)
	},
	"postgres.setting.category": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetCategory()).ToDataRes(types.String)
	},
	"postgres.setting.context": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetContext()).ToDataRes(types.String)
	},
	"postgres.setting.source": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetSource()).ToDataRes(types.String)
	},
	"postgres.setting.bootValue": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetBootValue()).ToDataRes(types.String)
	},
	"postgres.setting.resetValue": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetResetValue()).ToDataRes(types.String)
	},
	"postgres.setting.pendingRestart": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSetting).GetPendingRestart()).ToDataRes(types.Bool)
	},
	"postgres.hbaRule.lineNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetLineNumber()).ToDataRes(types.Int)
	},
	"postgres.hbaRule.type": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetType()).ToDataRes(types.String)
	},
	"postgres.hbaRule.databases": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetDatabases()).ToDataRes(types.Array(types.String))
	},
	"postgres.hbaRule.userNames": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetUserNames()).ToDataRes(types.Array(types.String))
	},
	"postgres.hbaRule.address": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetAddress()).ToDataRes(types.String)
	},
	"postgres.hbaRule.netmask": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetNetmask()).ToDataRes(types.String)
	},
	"postgres.hbaRule.authMethod": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetAuthMethod()).ToDataRes(types.String)
	},
	"postgres.hbaRule.options": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetOptions()).ToDataRes(types.Array(types.String))
	},
	"postgres.hbaRule.error": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresHbaRule).GetError()).ToDataRes(types.String)
	},
	"postgres.extension.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresExtension).GetName()).ToDataRes(types.String)
	},
	"postgres.extension.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresExtension).GetVersion()).ToDataRes(types.String)
	},
	"postgres.extension.schema": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresExtension).GetSchema()).ToDataRes(types.String)
	},
	"postgres.extension.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresExtension).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.tablespace.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTablespace).GetName()).ToDataRes(types.String)
	},
	"postgres.tablespace.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTablespace).GetOid()).ToDataRes(types.Int)
	},
	"postgres.tablespace.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTablespace).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.tablespace.location": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTablespace).GetLocation()).ToDataRes(types.String)
	},
	"postgres.tablespace.privileges": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresTablespace).GetPrivileges()).ToDataRes(types.Array(types.Resource("postgres.privilege")))
	},
	"postgres.foreignServer.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresForeignServer).GetName()).ToDataRes(types.String)
	},
	"postgres.foreignServer.type": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresForeignServer).GetType()).ToDataRes(types.String)
	},
	"postgres.foreignServer.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresForeignServer).GetVersion()).ToDataRes(types.String)
	},
	"postgres.foreignServer.fdwName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresForeignServer).GetFdwName()).ToDataRes(types.String)
	},
	"postgres.foreignServer.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresForeignServer).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.foreignServer.options": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresForeignServer).GetOptions()).ToDataRes(types.Array(types.String))
	},
	"postgres.foreignServer.userMappings": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresForeignServer).GetUserMappings()).ToDataRes(types.Array(types.Resource("postgres.userMapping")))
	},
	"postgres.userMapping.role": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresUserMapping).GetRole()).ToDataRes(types.String)
	},
	"postgres.userMapping.server": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresUserMapping).GetServer()).ToDataRes(types.String)
	},
	"postgres.userMapping.options": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresUserMapping).GetOptions()).ToDataRes(types.Array(types.String))
	},
	"postgres.replicationSlot.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresReplicationSlot).GetName()).ToDataRes(types.String)
	},
	"postgres.replicationSlot.slotType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresReplicationSlot).GetSlotType()).ToDataRes(types.String)
	},
	"postgres.replicationSlot.active": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresReplicationSlot).GetActive()).ToDataRes(types.Bool)
	},
	"postgres.replicationSlot.database": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresReplicationSlot).GetDatabase()).ToDataRes(types.String)
	},
	"postgres.replicationSlot.temporary": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresReplicationSlot).GetTemporary()).ToDataRes(types.Bool)
	},
	"postgres.publication.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPublication).GetName()).ToDataRes(types.String)
	},
	"postgres.publication.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPublication).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.publication.allTables": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPublication).GetAllTables()).ToDataRes(types.Bool)
	},
	"postgres.publication.insert": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPublication).GetInsert()).ToDataRes(types.Bool)
	},
	"postgres.publication.update": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPublication).GetUpdate()).ToDataRes(types.Bool)
	},
	"postgres.publication.delete": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPublication).GetDelete()).ToDataRes(types.Bool)
	},
	"postgres.publication.truncate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresPublication).GetTruncate()).ToDataRes(types.Bool)
	},
	"postgres.subscription.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSubscription).GetName()).ToDataRes(types.String)
	},
	"postgres.subscription.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSubscription).GetOwner()).ToDataRes(types.Resource("postgres.role"))
	},
	"postgres.subscription.enabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSubscription).GetEnabled()).ToDataRes(types.Bool)
	},
	"postgres.subscription.connectionSanitized": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresSubscription).GetConnectionSanitized()).ToDataRes(types.String)
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"postgres.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgres).__id, ok = v.Value.(string)
		return
	},
	"postgres.instance.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).__id, ok = v.Value.(string)
		return
	},
	"postgres.instance.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.instance.systemIdentifier": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).SystemIdentifier, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.instance.startTime": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).StartTime, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"postgres.instance.inRecovery": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).InRecovery, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.instance.ssl": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).Ssl, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.instance.passwordEncryption": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).PasswordEncryption, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.instance.listenAddresses": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).ListenAddresses, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.instance.settings": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).Settings, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.instance.roles": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).Roles, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.instance.databases": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).Databases, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.instance.tablespaces": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).Tablespaces, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.instance.hbaRules": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).HbaRules, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.instance.replicationSlots": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).ReplicationSlots, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.instance.subscriptions": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresInstance).Subscriptions, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.role.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).__id, ok = v.Value.(string)
		return
	},
	"postgres.role.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.role.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.role.isSuperuser": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).IsSuperuser, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.role.canLogin": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).CanLogin, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.role.createRole": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).CreateRole, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.role.createDb": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).CreateDb, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.role.isReplication": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).IsReplication, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.role.bypassRLS": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).BypassRLS, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.role.inheritsPrivileges": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).InheritsPrivileges, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.role.connectionLimit": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).ConnectionLimit, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.role.validUntil": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).ValidUntil, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"postgres.role.passwordType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).PasswordType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.role.memberOf": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).MemberOf, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.role.members": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).Members, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.role.config": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRole).Config, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.database.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).__id, ok = v.Value.(string)
		return
	},
	"postgres.database.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.database.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.database.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.database.encoding": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Encoding, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.database.collate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Collate, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.database.ctype": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Ctype, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.database.isTemplate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).IsTemplate, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.database.allowConnections": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).AllowConnections, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.database.connectionLimit": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).ConnectionLimit, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.database.privileges": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Privileges, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.database.schemas": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Schemas, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.database.functions": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Functions, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.database.extensions": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Extensions, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.database.foreignServers": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).ForeignServers, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.database.publications": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresDatabase).Publications, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.schema.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSchema).__id, ok = v.Value.(string)
		return
	},
	"postgres.schema.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSchema).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.schema.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSchema).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.schema.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSchema).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.schema.privileges": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSchema).Privileges, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.schema.tables": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSchema).Tables, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.table.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).__id, ok = v.Value.(string)
		return
	},
	"postgres.table.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.table.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.table.schema": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).Schema, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.table.kind": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).Kind, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.table.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.table.rowSecurityEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).RowSecurityEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.table.rowSecurityForced": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).RowSecurityForced, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.table.privileges": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).Privileges, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.table.policies": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTable).Policies, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.rlsPolicy.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRlsPolicy).__id, ok = v.Value.(string)
		return
	},
	"postgres.rlsPolicy.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRlsPolicy).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.rlsPolicy.command": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRlsPolicy).Command, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.rlsPolicy.permissive": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRlsPolicy).Permissive, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.rlsPolicy.roles": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRlsPolicy).Roles, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.rlsPolicy.usingExpression": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRlsPolicy).UsingExpression, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.rlsPolicy.checkExpression": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresRlsPolicy).CheckExpression, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.function.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresFunction).__id, ok = v.Value.(string)
		return
	},
	"postgres.function.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresFunction).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.function.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresFunction).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.function.schema": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresFunction).Schema, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.function.language": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresFunction).Language, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.function.isSecurityDefiner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresFunction).IsSecurityDefiner, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.function.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresFunction).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.function.privileges": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresFunction).Privileges, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.privilege.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPrivilege).__id, ok = v.Value.(string)
		return
	},
	"postgres.privilege.grantee": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPrivilege).Grantee, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.privilege.privilegeType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPrivilege).PrivilegeType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.privilege.isGrantable": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPrivilege).IsGrantable, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.setting.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).__id, ok = v.Value.(string)
		return
	},
	"postgres.setting.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.setting.setting": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).Setting, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.setting.unit": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).Unit, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.setting.category": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).Category, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.setting.context": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).Context, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.setting.source": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).Source, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.setting.bootValue": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).BootValue, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.setting.resetValue": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).ResetValue, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.setting.pendingRestart": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSetting).PendingRestart, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).__id, ok = v.Value.(string)
		return
	},
	"postgres.hbaRule.lineNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).LineNumber, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.type": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).Type, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.databases": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).Databases, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.userNames": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).UserNames, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.address": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).Address, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.netmask": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).Netmask, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.authMethod": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).AuthMethod, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.options": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).Options, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.hbaRule.error": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresHbaRule).Error, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.extension.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresExtension).__id, ok = v.Value.(string)
		return
	},
	"postgres.extension.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresExtension).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.extension.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresExtension).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.extension.schema": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresExtension).Schema, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.extension.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresExtension).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.tablespace.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTablespace).__id, ok = v.Value.(string)
		return
	},
	"postgres.tablespace.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTablespace).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.tablespace.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTablespace).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgres.tablespace.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTablespace).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.tablespace.location": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTablespace).Location, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.tablespace.privileges": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresTablespace).Privileges, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.foreignServer.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresForeignServer).__id, ok = v.Value.(string)
		return
	},
	"postgres.foreignServer.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresForeignServer).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.foreignServer.type": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresForeignServer).Type, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.foreignServer.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresForeignServer).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.foreignServer.fdwName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresForeignServer).FdwName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.foreignServer.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresForeignServer).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.foreignServer.options": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresForeignServer).Options, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.foreignServer.userMappings": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresForeignServer).UserMappings, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.userMapping.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresUserMapping).__id, ok = v.Value.(string)
		return
	},
	"postgres.userMapping.role": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresUserMapping).Role, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.userMapping.server": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresUserMapping).Server, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.userMapping.options": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresUserMapping).Options, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgres.replicationSlot.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresReplicationSlot).__id, ok = v.Value.(string)
		return
	},
	"postgres.replicationSlot.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresReplicationSlot).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.replicationSlot.slotType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresReplicationSlot).SlotType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.replicationSlot.active": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresReplicationSlot).Active, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.replicationSlot.database": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresReplicationSlot).Database, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.replicationSlot.temporary": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresReplicationSlot).Temporary, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.publication.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPublication).__id, ok = v.Value.(string)
		return
	},
	"postgres.publication.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPublication).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.publication.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPublication).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.publication.allTables": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPublication).AllTables, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.publication.insert": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPublication).Insert, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.publication.update": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPublication).Update, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.publication.delete": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPublication).Delete, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.publication.truncate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresPublication).Truncate, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.subscription.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSubscription).__id, ok = v.Value.(string)
		return
	},
	"postgres.subscription.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSubscription).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgres.subscription.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSubscription).Owner, ok = plugin.RawToTValue[*mqlPostgresRole](v.Value, v.Error)
		return
	},
	"postgres.subscription.enabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSubscription).Enabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgres.subscription.connectionSanitized": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresSubscription).ConnectionSanitized, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[postgres] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[postgres] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlPostgres for the postgres resource
type mqlPostgres struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresInternal it will be used here
}

// createPostgres creates a new instance of this resource
func createPostgres(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgres{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgres) MqlName() string {
	return "postgres"
}

func (c *mqlPostgres) MqlID() string {
	return c.__id
}

// mqlPostgresInstance for the postgres.instance resource
type mqlPostgresInstance struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresInstanceInternal it will be used here
	Version            plugin.TValue[string]
	SystemIdentifier   plugin.TValue[string]
	StartTime          plugin.TValue[*time.Time]
	InRecovery         plugin.TValue[bool]
	Ssl                plugin.TValue[bool]
	PasswordEncryption plugin.TValue[string]
	ListenAddresses    plugin.TValue[string]
	Settings           plugin.TValue[[]any]
	Roles              plugin.TValue[[]any]
	Databases          plugin.TValue[[]any]
	Tablespaces        plugin.TValue[[]any]
	HbaRules           plugin.TValue[[]any]
	ReplicationSlots   plugin.TValue[[]any]
	Subscriptions      plugin.TValue[[]any]
}

// createPostgresInstance creates a new instance of this resource
func createPostgresInstance(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresInstance{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.instance", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresInstance) MqlName() string {
	return "postgres.instance"
}

func (c *mqlPostgresInstance) MqlID() string {
	return c.__id
}

func (c *mqlPostgresInstance) GetVersion() *plugin.TValue[string] {
	return &c.Version
}

func (c *mqlPostgresInstance) GetSystemIdentifier() *plugin.TValue[string] {
	return &c.SystemIdentifier
}

func (c *mqlPostgresInstance) GetStartTime() *plugin.TValue[*time.Time] {
	return &c.StartTime
}

func (c *mqlPostgresInstance) GetInRecovery() *plugin.TValue[bool] {
	return &c.InRecovery
}

func (c *mqlPostgresInstance) GetSsl() *plugin.TValue[bool] {
	return &c.Ssl
}

func (c *mqlPostgresInstance) GetPasswordEncryption() *plugin.TValue[string] {
	return &c.PasswordEncryption
}

func (c *mqlPostgresInstance) GetListenAddresses() *plugin.TValue[string] {
	return &c.ListenAddresses
}

func (c *mqlPostgresInstance) GetSettings() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Settings, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.instance", c.__id, "settings")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.settings()
	})
}

func (c *mqlPostgresInstance) GetRoles() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Roles, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.instance", c.__id, "roles")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.roles()
	})
}

func (c *mqlPostgresInstance) GetDatabases() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Databases, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.instance", c.__id, "databases")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.databases()
	})
}

func (c *mqlPostgresInstance) GetTablespaces() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Tablespaces, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.instance", c.__id, "tablespaces")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.tablespaces()
	})
}

func (c *mqlPostgresInstance) GetHbaRules() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.HbaRules, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.instance", c.__id, "hbaRules")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.hbaRules()
	})
}

func (c *mqlPostgresInstance) GetReplicationSlots() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.ReplicationSlots, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.instance", c.__id, "replicationSlots")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.replicationSlots()
	})
}

func (c *mqlPostgresInstance) GetSubscriptions() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Subscriptions, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.instance", c.__id, "subscriptions")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.subscriptions()
	})
}

// mqlPostgresRole for the postgres.role resource
type mqlPostgresRole struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresRoleInternal it will be used here
	Name               plugin.TValue[string]
	Oid                plugin.TValue[int64]
	IsSuperuser        plugin.TValue[bool]
	CanLogin           plugin.TValue[bool]
	CreateRole         plugin.TValue[bool]
	CreateDb           plugin.TValue[bool]
	IsReplication      plugin.TValue[bool]
	BypassRLS          plugin.TValue[bool]
	InheritsPrivileges plugin.TValue[bool]
	ConnectionLimit    plugin.TValue[int64]
	ValidUntil         plugin.TValue[*time.Time]
	PasswordType       plugin.TValue[string]
	MemberOf           plugin.TValue[[]any]
	Members            plugin.TValue[[]any]
	Config             plugin.TValue[[]any]
}

// createPostgresRole creates a new instance of this resource
func createPostgresRole(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresRole{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.role", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresRole) MqlName() string {
	return "postgres.role"
}

func (c *mqlPostgresRole) MqlID() string {
	return c.__id
}

func (c *mqlPostgresRole) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresRole) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresRole) GetIsSuperuser() *plugin.TValue[bool] {
	return &c.IsSuperuser
}

func (c *mqlPostgresRole) GetCanLogin() *plugin.TValue[bool] {
	return &c.CanLogin
}

func (c *mqlPostgresRole) GetCreateRole() *plugin.TValue[bool] {
	return &c.CreateRole
}

func (c *mqlPostgresRole) GetCreateDb() *plugin.TValue[bool] {
	return &c.CreateDb
}

func (c *mqlPostgresRole) GetIsReplication() *plugin.TValue[bool] {
	return &c.IsReplication
}

func (c *mqlPostgresRole) GetBypassRLS() *plugin.TValue[bool] {
	return &c.BypassRLS
}

func (c *mqlPostgresRole) GetInheritsPrivileges() *plugin.TValue[bool] {
	return &c.InheritsPrivileges
}

func (c *mqlPostgresRole) GetConnectionLimit() *plugin.TValue[int64] {
	return &c.ConnectionLimit
}

func (c *mqlPostgresRole) GetValidUntil() *plugin.TValue[*time.Time] {
	return &c.ValidUntil
}

func (c *mqlPostgresRole) GetPasswordType() *plugin.TValue[string] {
	return &c.PasswordType
}

func (c *mqlPostgresRole) GetMemberOf() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.MemberOf, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.role", c.__id, "memberOf")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.memberOf()
	})
}

func (c *mqlPostgresRole) GetMembers() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Members, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.role", c.__id, "members")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.members()
	})
}

func (c *mqlPostgresRole) GetConfig() *plugin.TValue[[]any] {
	return &c.Config
}

// mqlPostgresDatabase for the postgres.database resource
type mqlPostgresDatabase struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresDatabaseInternal
	Name             plugin.TValue[string]
	Oid              plugin.TValue[int64]
	Owner            plugin.TValue[*mqlPostgresRole]
	Encoding         plugin.TValue[string]
	Collate          plugin.TValue[string]
	Ctype            plugin.TValue[string]
	IsTemplate       plugin.TValue[bool]
	AllowConnections plugin.TValue[bool]
	ConnectionLimit  plugin.TValue[int64]
	Privileges       plugin.TValue[[]any]
	Schemas          plugin.TValue[[]any]
	Functions        plugin.TValue[[]any]
	Extensions       plugin.TValue[[]any]
	ForeignServers   plugin.TValue[[]any]
	Publications     plugin.TValue[[]any]
}

// createPostgresDatabase creates a new instance of this resource
func createPostgresDatabase(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresDatabase{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.database", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresDatabase) MqlName() string {
	return "postgres.database"
}

func (c *mqlPostgresDatabase) MqlID() string {
	return c.__id
}

func (c *mqlPostgresDatabase) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresDatabase) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresDatabase) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.database", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

func (c *mqlPostgresDatabase) GetEncoding() *plugin.TValue[string] {
	return &c.Encoding
}

func (c *mqlPostgresDatabase) GetCollate() *plugin.TValue[string] {
	return &c.Collate
}

func (c *mqlPostgresDatabase) GetCtype() *plugin.TValue[string] {
	return &c.Ctype
}

func (c *mqlPostgresDatabase) GetIsTemplate() *plugin.TValue[bool] {
	return &c.IsTemplate
}

func (c *mqlPostgresDatabase) GetAllowConnections() *plugin.TValue[bool] {
	return &c.AllowConnections
}

func (c *mqlPostgresDatabase) GetConnectionLimit() *plugin.TValue[int64] {
	return &c.ConnectionLimit
}

func (c *mqlPostgresDatabase) GetPrivileges() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Privileges, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.database", c.__id, "privileges")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.privileges()
	})
}

func (c *mqlPostgresDatabase) GetSchemas() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Schemas, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.database", c.__id, "schemas")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.schemas()
	})
}

func (c *mqlPostgresDatabase) GetFunctions() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Functions, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.database", c.__id, "functions")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.functions()
	})
}

func (c *mqlPostgresDatabase) GetExtensions() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Extensions, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.database", c.__id, "extensions")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.extensions()
	})
}

func (c *mqlPostgresDatabase) GetForeignServers() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.ForeignServers, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.database", c.__id, "foreignServers")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.foreignServers()
	})
}

func (c *mqlPostgresDatabase) GetPublications() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Publications, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.database", c.__id, "publications")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.publications()
	})
}

// mqlPostgresSchema for the postgres.schema resource
type mqlPostgresSchema struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresSchemaInternal
	Name       plugin.TValue[string]
	Oid        plugin.TValue[int64]
	Owner      plugin.TValue[*mqlPostgresRole]
	Privileges plugin.TValue[[]any]
	Tables     plugin.TValue[[]any]
}

// createPostgresSchema creates a new instance of this resource
func createPostgresSchema(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresSchema{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.schema", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresSchema) MqlName() string {
	return "postgres.schema"
}

func (c *mqlPostgresSchema) MqlID() string {
	return c.__id
}

func (c *mqlPostgresSchema) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresSchema) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresSchema) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.schema", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

func (c *mqlPostgresSchema) GetPrivileges() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Privileges, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.schema", c.__id, "privileges")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.privileges()
	})
}

func (c *mqlPostgresSchema) GetTables() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Tables, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.schema", c.__id, "tables")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.tables()
	})
}

// mqlPostgresTable for the postgres.table resource
type mqlPostgresTable struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresTableInternal
	Name               plugin.TValue[string]
	Oid                plugin.TValue[int64]
	Schema             plugin.TValue[string]
	Kind               plugin.TValue[string]
	Owner              plugin.TValue[*mqlPostgresRole]
	RowSecurityEnabled plugin.TValue[bool]
	RowSecurityForced  plugin.TValue[bool]
	Privileges         plugin.TValue[[]any]
	Policies           plugin.TValue[[]any]
}

// createPostgresTable creates a new instance of this resource
func createPostgresTable(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresTable{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.table", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresTable) MqlName() string {
	return "postgres.table"
}

func (c *mqlPostgresTable) MqlID() string {
	return c.__id
}

func (c *mqlPostgresTable) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresTable) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresTable) GetSchema() *plugin.TValue[string] {
	return &c.Schema
}

func (c *mqlPostgresTable) GetKind() *plugin.TValue[string] {
	return &c.Kind
}

func (c *mqlPostgresTable) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.table", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

func (c *mqlPostgresTable) GetRowSecurityEnabled() *plugin.TValue[bool] {
	return &c.RowSecurityEnabled
}

func (c *mqlPostgresTable) GetRowSecurityForced() *plugin.TValue[bool] {
	return &c.RowSecurityForced
}

func (c *mqlPostgresTable) GetPrivileges() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Privileges, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.table", c.__id, "privileges")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.privileges()
	})
}

func (c *mqlPostgresTable) GetPolicies() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Policies, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.table", c.__id, "policies")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.policies()
	})
}

// mqlPostgresRlsPolicy for the postgres.rlsPolicy resource
type mqlPostgresRlsPolicy struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresRlsPolicyInternal it will be used here
	Name            plugin.TValue[string]
	Command         plugin.TValue[string]
	Permissive      plugin.TValue[bool]
	Roles           plugin.TValue[[]any]
	UsingExpression plugin.TValue[string]
	CheckExpression plugin.TValue[string]
}

// createPostgresRlsPolicy creates a new instance of this resource
func createPostgresRlsPolicy(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresRlsPolicy{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.rlsPolicy", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresRlsPolicy) MqlName() string {
	return "postgres.rlsPolicy"
}

func (c *mqlPostgresRlsPolicy) MqlID() string {
	return c.__id
}

func (c *mqlPostgresRlsPolicy) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresRlsPolicy) GetCommand() *plugin.TValue[string] {
	return &c.Command
}

func (c *mqlPostgresRlsPolicy) GetPermissive() *plugin.TValue[bool] {
	return &c.Permissive
}

func (c *mqlPostgresRlsPolicy) GetRoles() *plugin.TValue[[]any] {
	return &c.Roles
}

func (c *mqlPostgresRlsPolicy) GetUsingExpression() *plugin.TValue[string] {
	return &c.UsingExpression
}

func (c *mqlPostgresRlsPolicy) GetCheckExpression() *plugin.TValue[string] {
	return &c.CheckExpression
}

// mqlPostgresFunction for the postgres.function resource
type mqlPostgresFunction struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresFunctionInternal
	Name              plugin.TValue[string]
	Oid               plugin.TValue[int64]
	Schema            plugin.TValue[string]
	Language          plugin.TValue[string]
	IsSecurityDefiner plugin.TValue[bool]
	Owner             plugin.TValue[*mqlPostgresRole]
	Privileges        plugin.TValue[[]any]
}

// createPostgresFunction creates a new instance of this resource
func createPostgresFunction(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresFunction{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.function", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresFunction) MqlName() string {
	return "postgres.function"
}

func (c *mqlPostgresFunction) MqlID() string {
	return c.__id
}

func (c *mqlPostgresFunction) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresFunction) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresFunction) GetSchema() *plugin.TValue[string] {
	return &c.Schema
}

func (c *mqlPostgresFunction) GetLanguage() *plugin.TValue[string] {
	return &c.Language
}

func (c *mqlPostgresFunction) GetIsSecurityDefiner() *plugin.TValue[bool] {
	return &c.IsSecurityDefiner
}

func (c *mqlPostgresFunction) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.function", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

func (c *mqlPostgresFunction) GetPrivileges() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Privileges, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.function", c.__id, "privileges")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.privileges()
	})
}

// mqlPostgresPrivilege for the postgres.privilege resource
type mqlPostgresPrivilege struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresPrivilegeInternal it will be used here
	Grantee       plugin.TValue[string]
	PrivilegeType plugin.TValue[string]
	IsGrantable   plugin.TValue[bool]
}

// createPostgresPrivilege creates a new instance of this resource
func createPostgresPrivilege(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresPrivilege{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.privilege", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresPrivilege) MqlName() string {
	return "postgres.privilege"
}

func (c *mqlPostgresPrivilege) MqlID() string {
	return c.__id
}

func (c *mqlPostgresPrivilege) GetGrantee() *plugin.TValue[string] {
	return &c.Grantee
}

func (c *mqlPostgresPrivilege) GetPrivilegeType() *plugin.TValue[string] {
	return &c.PrivilegeType
}

func (c *mqlPostgresPrivilege) GetIsGrantable() *plugin.TValue[bool] {
	return &c.IsGrantable
}

// mqlPostgresSetting for the postgres.setting resource
type mqlPostgresSetting struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresSettingInternal it will be used here
	Name           plugin.TValue[string]
	Setting        plugin.TValue[string]
	Unit           plugin.TValue[string]
	Category       plugin.TValue[string]
	Context        plugin.TValue[string]
	Source         plugin.TValue[string]
	BootValue      plugin.TValue[string]
	ResetValue     plugin.TValue[string]
	PendingRestart plugin.TValue[bool]
}

// createPostgresSetting creates a new instance of this resource
func createPostgresSetting(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresSetting{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.setting", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresSetting) MqlName() string {
	return "postgres.setting"
}

func (c *mqlPostgresSetting) MqlID() string {
	return c.__id
}

func (c *mqlPostgresSetting) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresSetting) GetSetting() *plugin.TValue[string] {
	return &c.Setting
}

func (c *mqlPostgresSetting) GetUnit() *plugin.TValue[string] {
	return &c.Unit
}

func (c *mqlPostgresSetting) GetCategory() *plugin.TValue[string] {
	return &c.Category
}

func (c *mqlPostgresSetting) GetContext() *plugin.TValue[string] {
	return &c.Context
}

func (c *mqlPostgresSetting) GetSource() *plugin.TValue[string] {
	return &c.Source
}

func (c *mqlPostgresSetting) GetBootValue() *plugin.TValue[string] {
	return &c.BootValue
}

func (c *mqlPostgresSetting) GetResetValue() *plugin.TValue[string] {
	return &c.ResetValue
}

func (c *mqlPostgresSetting) GetPendingRestart() *plugin.TValue[bool] {
	return &c.PendingRestart
}

// mqlPostgresHbaRule for the postgres.hbaRule resource
type mqlPostgresHbaRule struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresHbaRuleInternal it will be used here
	LineNumber plugin.TValue[int64]
	Type       plugin.TValue[string]
	Databases  plugin.TValue[[]any]
	UserNames  plugin.TValue[[]any]
	Address    plugin.TValue[string]
	Netmask    plugin.TValue[string]
	AuthMethod plugin.TValue[string]
	Options    plugin.TValue[[]any]
	Error      plugin.TValue[string]
}

// createPostgresHbaRule creates a new instance of this resource
func createPostgresHbaRule(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresHbaRule{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.hbaRule", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresHbaRule) MqlName() string {
	return "postgres.hbaRule"
}

func (c *mqlPostgresHbaRule) MqlID() string {
	return c.__id
}

func (c *mqlPostgresHbaRule) GetLineNumber() *plugin.TValue[int64] {
	return &c.LineNumber
}

func (c *mqlPostgresHbaRule) GetType() *plugin.TValue[string] {
	return &c.Type
}

func (c *mqlPostgresHbaRule) GetDatabases() *plugin.TValue[[]any] {
	return &c.Databases
}

func (c *mqlPostgresHbaRule) GetUserNames() *plugin.TValue[[]any] {
	return &c.UserNames
}

func (c *mqlPostgresHbaRule) GetAddress() *plugin.TValue[string] {
	return &c.Address
}

func (c *mqlPostgresHbaRule) GetNetmask() *plugin.TValue[string] {
	return &c.Netmask
}

func (c *mqlPostgresHbaRule) GetAuthMethod() *plugin.TValue[string] {
	return &c.AuthMethod
}

func (c *mqlPostgresHbaRule) GetOptions() *plugin.TValue[[]any] {
	return &c.Options
}

func (c *mqlPostgresHbaRule) GetError() *plugin.TValue[string] {
	return &c.Error
}

// mqlPostgresExtension for the postgres.extension resource
type mqlPostgresExtension struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresExtensionInternal
	Name    plugin.TValue[string]
	Version plugin.TValue[string]
	Schema  plugin.TValue[string]
	Owner   plugin.TValue[*mqlPostgresRole]
}

// createPostgresExtension creates a new instance of this resource
func createPostgresExtension(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresExtension{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.extension", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresExtension) MqlName() string {
	return "postgres.extension"
}

func (c *mqlPostgresExtension) MqlID() string {
	return c.__id
}

func (c *mqlPostgresExtension) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresExtension) GetVersion() *plugin.TValue[string] {
	return &c.Version
}

func (c *mqlPostgresExtension) GetSchema() *plugin.TValue[string] {
	return &c.Schema
}

func (c *mqlPostgresExtension) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.extension", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

// mqlPostgresTablespace for the postgres.tablespace resource
type mqlPostgresTablespace struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresTablespaceInternal
	Name       plugin.TValue[string]
	Oid        plugin.TValue[int64]
	Owner      plugin.TValue[*mqlPostgresRole]
	Location   plugin.TValue[string]
	Privileges plugin.TValue[[]any]
}

// createPostgresTablespace creates a new instance of this resource
func createPostgresTablespace(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresTablespace{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.tablespace", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresTablespace) MqlName() string {
	return "postgres.tablespace"
}

func (c *mqlPostgresTablespace) MqlID() string {
	return c.__id
}

func (c *mqlPostgresTablespace) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresTablespace) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresTablespace) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.tablespace", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

func (c *mqlPostgresTablespace) GetLocation() *plugin.TValue[string] {
	return &c.Location
}

func (c *mqlPostgresTablespace) GetPrivileges() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Privileges, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.tablespace", c.__id, "privileges")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.privileges()
	})
}

// mqlPostgresForeignServer for the postgres.foreignServer resource
type mqlPostgresForeignServer struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresForeignServerInternal
	Name         plugin.TValue[string]
	Type         plugin.TValue[string]
	Version      plugin.TValue[string]
	FdwName      plugin.TValue[string]
	Owner        plugin.TValue[*mqlPostgresRole]
	Options      plugin.TValue[[]any]
	UserMappings plugin.TValue[[]any]
}

// createPostgresForeignServer creates a new instance of this resource
func createPostgresForeignServer(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresForeignServer{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.foreignServer", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresForeignServer) MqlName() string {
	return "postgres.foreignServer"
}

func (c *mqlPostgresForeignServer) MqlID() string {
	return c.__id
}

func (c *mqlPostgresForeignServer) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresForeignServer) GetType() *plugin.TValue[string] {
	return &c.Type
}

func (c *mqlPostgresForeignServer) GetVersion() *plugin.TValue[string] {
	return &c.Version
}

func (c *mqlPostgresForeignServer) GetFdwName() *plugin.TValue[string] {
	return &c.FdwName
}

func (c *mqlPostgresForeignServer) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.foreignServer", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

func (c *mqlPostgresForeignServer) GetOptions() *plugin.TValue[[]any] {
	return &c.Options
}

func (c *mqlPostgresForeignServer) GetUserMappings() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.UserMappings, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.foreignServer", c.__id, "userMappings")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.userMappings()
	})
}

// mqlPostgresUserMapping for the postgres.userMapping resource
type mqlPostgresUserMapping struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresUserMappingInternal it will be used here
	Role    plugin.TValue[string]
	Server  plugin.TValue[string]
	Options plugin.TValue[[]any]
}

// createPostgresUserMapping creates a new instance of this resource
func createPostgresUserMapping(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresUserMapping{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.userMapping", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresUserMapping) MqlName() string {
	return "postgres.userMapping"
}

func (c *mqlPostgresUserMapping) MqlID() string {
	return c.__id
}

func (c *mqlPostgresUserMapping) GetRole() *plugin.TValue[string] {
	return &c.Role
}

func (c *mqlPostgresUserMapping) GetServer() *plugin.TValue[string] {
	return &c.Server
}

func (c *mqlPostgresUserMapping) GetOptions() *plugin.TValue[[]any] {
	return &c.Options
}

// mqlPostgresReplicationSlot for the postgres.replicationSlot resource
type mqlPostgresReplicationSlot struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresReplicationSlotInternal it will be used here
	Name      plugin.TValue[string]
	SlotType  plugin.TValue[string]
	Active    plugin.TValue[bool]
	Database  plugin.TValue[string]
	Temporary plugin.TValue[bool]
}

// createPostgresReplicationSlot creates a new instance of this resource
func createPostgresReplicationSlot(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresReplicationSlot{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.replicationSlot", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresReplicationSlot) MqlName() string {
	return "postgres.replicationSlot"
}

func (c *mqlPostgresReplicationSlot) MqlID() string {
	return c.__id
}

func (c *mqlPostgresReplicationSlot) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresReplicationSlot) GetSlotType() *plugin.TValue[string] {
	return &c.SlotType
}

func (c *mqlPostgresReplicationSlot) GetActive() *plugin.TValue[bool] {
	return &c.Active
}

func (c *mqlPostgresReplicationSlot) GetDatabase() *plugin.TValue[string] {
	return &c.Database
}

func (c *mqlPostgresReplicationSlot) GetTemporary() *plugin.TValue[bool] {
	return &c.Temporary
}

// mqlPostgresPublication for the postgres.publication resource
type mqlPostgresPublication struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresPublicationInternal
	Name      plugin.TValue[string]
	Owner     plugin.TValue[*mqlPostgresRole]
	AllTables plugin.TValue[bool]
	Insert    plugin.TValue[bool]
	Update    plugin.TValue[bool]
	Delete    plugin.TValue[bool]
	Truncate  plugin.TValue[bool]
}

// createPostgresPublication creates a new instance of this resource
func createPostgresPublication(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresPublication{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.publication", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresPublication) MqlName() string {
	return "postgres.publication"
}

func (c *mqlPostgresPublication) MqlID() string {
	return c.__id
}

func (c *mqlPostgresPublication) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresPublication) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.publication", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

func (c *mqlPostgresPublication) GetAllTables() *plugin.TValue[bool] {
	return &c.AllTables
}

func (c *mqlPostgresPublication) GetInsert() *plugin.TValue[bool] {
	return &c.Insert
}

func (c *mqlPostgresPublication) GetUpdate() *plugin.TValue[bool] {
	return &c.Update
}

func (c *mqlPostgresPublication) GetDelete() *plugin.TValue[bool] {
	return &c.Delete
}

func (c *mqlPostgresPublication) GetTruncate() *plugin.TValue[bool] {
	return &c.Truncate
}

// mqlPostgresSubscription for the postgres.subscription resource
type mqlPostgresSubscription struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlPostgresSubscriptionInternal
	Name                plugin.TValue[string]
	Owner               plugin.TValue[*mqlPostgresRole]
	Enabled             plugin.TValue[bool]
	ConnectionSanitized plugin.TValue[string]
}

// createPostgresSubscription creates a new instance of this resource
func createPostgresSubscription(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresSubscription{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgres.subscription", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresSubscription) MqlName() string {
	return "postgres.subscription"
}

func (c *mqlPostgresSubscription) MqlID() string {
	return c.__id
}

func (c *mqlPostgresSubscription) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresSubscription) GetOwner() *plugin.TValue[*mqlPostgresRole] {
	return plugin.GetOrCompute[*mqlPostgresRole](&c.Owner, func() (*mqlPostgresRole, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgres.subscription", c.__id, "owner")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlPostgresRole), nil
			}
		}

		return c.owner()
	})
}

func (c *mqlPostgresSubscription) GetEnabled() *plugin.TValue[bool] {
	return &c.Enabled
}

func (c *mqlPostgresSubscription) GetConnectionSanitized() *plugin.TValue[string] {
	return &c.ConnectionSanitized
}
