// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Docker struct {
	Images    []DockerImage     `json:"images"`
	Container []DockerContainer `json:"container"`
}

type DockerContainer struct {
	ID      string     `json:"id"`
	Command string     `json:"command"`
	Image   string     `json:"image"`
	Imageid string     `json:"imageid"`
	Names   []string   `json:"names"`
	State   string     `json:"state"`
	Status  string     `json:"status"`
	Labels  []KeyValue `json:"labels"`
}

type File struct {
	Path    *string `json:"path"`
	Content *string `json:"content"`
	Exists  bool    `json:"exists"`
}

type GcpCompute struct {
	Instances []GcpComputeInstance `json:"instances"`
	Zones     []GcpZone            `json:"zones"`
}

type GcpComputeInstance struct {
	Project string     `json:"project"`
	Zone    string     `json:"zone"`
	ID      string     `json:"id"`
	Name    string     `json:"name"`
	Kind    string     `json:"kind"`
	Status  string     `json:"status"`
	Labels  []KeyValue `json:"labels"`
}

type GcpProject struct {
	Name   string     `json:"name"`
	ID     string     `json:"id"`
	Number string     `json:"number"`
	Labels []KeyValue `json:"labels"`
}

type GcpStorage struct {
	Buckets []GcpStorageBucket `json:"buckets"`
}

type GcpStorageBucket struct {
	Project      string     `json:"project"`
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	Location     string     `json:"location"`
	Storageclass string     `json:"storageclass"`
	Labels       []KeyValue `json:"labels"`
}

type GcpZone struct {
	Name   string `json:"name"`
	Region string `json:"region"`
	Status string `json:"status"`
}

type GoogleCloudPlatform struct {
	Compute  *GcpCompute  `json:"compute"`
	Storage  *GcpStorage  `json:"storage"`
	Projects []GcpProject `json:"projects"`
}

type Kernel struct {
	Parameters []KeyValue `json:"parameters"`
}

type KeyValue struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}

type Mondoo struct {
	Version string `json:"version"`
	Build   string `json:"build"`
}

type Package struct {
	Name        string `json:"name"`
	Version     string `json:"version"`
	Arch        string `json:"arch"`
	Format      string `json:"format"`
	Description string `json:"description"`
	Status      string `json:"status"`
}

type Platform struct {
	Name    string   `json:"name"`
	Title   string   `json:"title"`
	Family  []string `json:"family"`
	Release string   `json:"release"`
	Arch    string   `json:"arch"`
}

type Service struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Installed   bool   `json:"installed"`
	Running     bool   `json:"running"`
	Enabled     bool   `json:"enabled"`
	Type        string `json:"type"`
}

type SSHConfig struct {
	Path   string     `json:"path"`
	File   *File      `json:"file"`
	Params []KeyValue `json:"params"`
}

type Sshd struct {
	Config *SSHConfig `json:"config"`
}
