// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package registry

import (
	"errors"
	"fmt"
	"runtime"
	"strings"
	"sync"
)

// RegistryHandler allows for loading and unloading of registry keys from files. It also allows for looking up registry keys and values.
type RegistryHandler struct {
	// a map of currently loaded registries.
	// the id is the registry's id (e.g. "SOFTWARE") and the value is the path to the loaded key (e.g. "TmpReg_SOFTWARE")
	registries map[string]string
	lock       sync.Mutex
}

const (
	subkeyPrefix = "TMPREG"
)

func NewRegistryHandler() *RegistryHandler {
	return &RegistryHandler{
		registries: make(map[string]string),
	}
}

// Loads the given registry file into the registry handler under a subkey, generated by buildSubKeyPath.
// The subkey file is indicated by the filepath parameter.
// Only known registry files (see KnownRegistryFiles) can be loaded.
func (r *RegistryHandler) LoadSubkey(registryId, filepath string) error {
	if runtime.GOOS != "windows" {
		return errors.New("loading of registry subkeys is only supported on windows")
	}

	r.lock.Lock()
	defer r.lock.Unlock()
	// sanity check, make sure we only try and load registry files we know of
	if _, ok := KnownRegistryFiles[registryId]; !ok {
		return errors.New("invalid registry id")
	}
	if _, ok := r.registries[registryId]; ok {
		return nil
	}
	// format the registry path
	key := buildSubKeyPath(registryId)
	err := LoadRegistrySubkey(key, filepath)
	if err != nil {
		return err
	}
	r.registries[registryId] = key
	return nil
}

// we use the name of the registry file as an id, e.g. "SOFTWARE"
// we combine this with the prefix to get a subkey like "TmpReg_SOFTWARE"
func buildSubKeyPath(registryId string) string {
	return fmt.Sprintf("%s_%s", subkeyPrefix, registryId)
}

// userRegistryID derives a stable registry id for a per-user hive from the
// user's SID. The leading "USER_" namespaces it away from the KnownRegistryFiles
// ids (SOFTWARE, SYSTEM, ...) so the two never collide.
func userRegistryID(sid string) string {
	return "USER_" + sid
}

// LoadUserHive loads a per-user NTUSER.DAT hive into the handler, keyed by the
// user's SID. Unlike LoadSubkey it is not restricted to KnownRegistryFiles — the
// caller supplies an arbitrary NTUSER.DAT path (typically user.ntuserDat), which
// is how we read the registry of a user who is not currently logged in (no live
// HKEY_USERS\<sid> hive). Loading is idempotent: a hive already loaded for the
// SID is a no-op, so concurrent reads of the same user coalesce onto one load.
func (r *RegistryHandler) LoadUserHive(sid, filepath string) error {
	if sid == "" {
		return errors.New("cannot load user hive: empty sid")
	}
	if filepath == "" {
		return errors.New("cannot load user hive: empty NTUSER.DAT path")
	}
	if runtime.GOOS != "windows" {
		return errors.New("loading of registry subkeys is only supported on windows")
	}

	r.lock.Lock()
	defer r.lock.Unlock()
	id := userRegistryID(sid)
	if _, ok := r.registries[id]; ok {
		return nil
	}
	key := buildSubKeyPath(id)
	if err := LoadRegistrySubkey(key, filepath); err != nil {
		return err
	}
	r.registries[id] = key
	return nil
}

// GetUserHiveKeyItems returns the registry items at `path` (relative to the hive
// root) for a user hive previously loaded with LoadUserHive.
func (r *RegistryHandler) GetUserHiveKeyItems(sid, path string) ([]RegistryKeyItem, error) {
	regPath, err := r.userHiveKeyPath(sid, path)
	if err != nil {
		return nil, err
	}
	return GetNativeRegistryKeyItems(regPath)
}

// GetUserHiveKeyChildren returns the child keys at `path` (relative to the hive
// root) for a user hive previously loaded with LoadUserHive.
func (r *RegistryHandler) GetUserHiveKeyChildren(sid, path string) ([]RegistryKeyChild, error) {
	regPath, err := r.userHiveKeyPath(sid, path)
	if err != nil {
		return nil, err
	}
	return GetNativeRegistryKeyChildren(regPath)
}

// userHiveKeyPath builds the fully-qualified HKLM path to `path` under the loaded
// user hive for `sid`. Loaded hives are mounted under HKLM (see getRegistryPath),
// so we always prefix with HKLM here.
func (r *RegistryHandler) userHiveKeyPath(sid, path string) (string, error) {
	r.lock.Lock()
	regRoot, ok := r.registries[userRegistryID(sid)]
	r.lock.Unlock()
	if !ok {
		return "", fmt.Errorf("registry hive for %s not loaded", sid)
	}
	root := fmt.Sprintf("HKLM\\%s", regRoot)
	path = strings.Trim(path, "\\")
	if path == "" {
		return root, nil
	}
	return fmt.Sprintf("%s\\%s", root, path), nil
}

// Unloads all the subkeys, that were loaded by the handler.
func (r *RegistryHandler) UnloadSubkeys() error {
	r.lock.Lock()
	defer r.lock.Unlock()
	for id, regPath := range r.registries {
		err := UnloadRegistrySubkey(regPath)
		if err != nil {
			return err
		}
		delete(r.registries, id)
	}
	return nil
}

// Gets a fully qualified registry path for a given registry id, including the root (HKLM).
func (r *RegistryHandler) getRegistryPath(id string) (string, error) {
	if path, ok := r.registries[id]; ok {
		// we always point the syscalls to HKEY_LOCAL_MACHINE so we can safely prefix it here
		return fmt.Sprintf("HKLM\\%s", path), nil
	}
	return "", fmt.Errorf("registry %s not loaded", id)
}

// Gets a fully qualified registry key path for a given registry id and key.
// E.g. if the registry id is "SOFTWARE" and the key is "Microsoft", the result will be "HKLM\TmpReg_SOFTWARE\Microsoft".
func (r *RegistryHandler) getRegistryKeyPath(id string, key string) (string, error) {
	root, err := r.getRegistryPath(id)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s\\%s", root, key), nil
}

func (r *RegistryHandler) GetRegistryItemValue(registryId string, path, key string) (RegistryKeyItem, error) {
	regPath, err := r.getRegistryKeyPath(registryId, path)
	if err != nil {
		return RegistryKeyItem{}, err
	}
	return GetNativeRegistryKeyItem(regPath, key)
}

func (r *RegistryHandler) GetNativeRegistryKeyChildren(registryId string, path string) ([]RegistryKeyChild, error) {
	regPath, err := r.getRegistryKeyPath(registryId, path)
	if err != nil {
		return nil, err
	}
	return GetNativeRegistryKeyChildren(regPath)
}
