// Package bwapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bwapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DeviceType.
const (
	DeviceTypeN0  DeviceType = 0
	DeviceTypeN1  DeviceType = 1
	DeviceTypeN10 DeviceType = 10
	DeviceTypeN11 DeviceType = 11
	DeviceTypeN12 DeviceType = 12
	DeviceTypeN13 DeviceType = 13
	DeviceTypeN14 DeviceType = 14
	DeviceTypeN15 DeviceType = 15
	DeviceTypeN16 DeviceType = 16
	DeviceTypeN17 DeviceType = 17
	DeviceTypeN18 DeviceType = 18
	DeviceTypeN19 DeviceType = 19
	DeviceTypeN2  DeviceType = 2
	DeviceTypeN20 DeviceType = 20
	DeviceTypeN3  DeviceType = 3
	DeviceTypeN4  DeviceType = 4
	DeviceTypeN5  DeviceType = 5
	DeviceTypeN6  DeviceType = 6
	DeviceTypeN7  DeviceType = 7
	DeviceTypeN8  DeviceType = 8
	DeviceTypeN9  DeviceType = 9
)

// Valid indicates whether the value is a known member of the DeviceType enum.
func (e DeviceType) Valid() bool {
	switch e {
	case DeviceTypeN0:
		return true
	case DeviceTypeN1:
		return true
	case DeviceTypeN10:
		return true
	case DeviceTypeN11:
		return true
	case DeviceTypeN12:
		return true
	case DeviceTypeN13:
		return true
	case DeviceTypeN14:
		return true
	case DeviceTypeN15:
		return true
	case DeviceTypeN16:
		return true
	case DeviceTypeN17:
		return true
	case DeviceTypeN18:
		return true
	case DeviceTypeN19:
		return true
	case DeviceTypeN2:
		return true
	case DeviceTypeN20:
		return true
	case DeviceTypeN3:
		return true
	case DeviceTypeN4:
		return true
	case DeviceTypeN5:
		return true
	case DeviceTypeN6:
		return true
	case DeviceTypeN7:
		return true
	case DeviceTypeN8:
		return true
	case DeviceTypeN9:
		return true
	default:
		return false
	}
}

// Defines values for EventType.
const (
	N1000 EventType = 1000
	N1001 EventType = 1001
	N1002 EventType = 1002
	N1003 EventType = 1003
	N1004 EventType = 1004
	N1005 EventType = 1005
	N1006 EventType = 1006
	N1007 EventType = 1007
	N1100 EventType = 1100
	N1101 EventType = 1101
	N1102 EventType = 1102
	N1103 EventType = 1103
	N1104 EventType = 1104
	N1105 EventType = 1105
	N1106 EventType = 1106
	N1107 EventType = 1107
	N1108 EventType = 1108
	N1109 EventType = 1109
	N1110 EventType = 1110
	N1111 EventType = 1111
	N1112 EventType = 1112
	N1113 EventType = 1113
	N1114 EventType = 1114
	N1115 EventType = 1115
	N1116 EventType = 1116
	N1300 EventType = 1300
	N1301 EventType = 1301
	N1302 EventType = 1302
	N1400 EventType = 1400
	N1401 EventType = 1401
	N1402 EventType = 1402
	N1500 EventType = 1500
	N1501 EventType = 1501
	N1502 EventType = 1502
	N1503 EventType = 1503
	N1504 EventType = 1504
	N1600 EventType = 1600
	N1601 EventType = 1601
	N1700 EventType = 1700
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case N1000:
		return true
	case N1001:
		return true
	case N1002:
		return true
	case N1003:
		return true
	case N1004:
		return true
	case N1005:
		return true
	case N1006:
		return true
	case N1007:
		return true
	case N1100:
		return true
	case N1101:
		return true
	case N1102:
		return true
	case N1103:
		return true
	case N1104:
		return true
	case N1105:
		return true
	case N1106:
		return true
	case N1107:
		return true
	case N1108:
		return true
	case N1109:
		return true
	case N1110:
		return true
	case N1111:
		return true
	case N1112:
		return true
	case N1113:
		return true
	case N1114:
		return true
	case N1115:
		return true
	case N1116:
		return true
	case N1300:
		return true
	case N1301:
		return true
	case N1302:
		return true
	case N1400:
		return true
	case N1401:
		return true
	case N1402:
		return true
	case N1500:
		return true
	case N1501:
		return true
	case N1502:
		return true
	case N1503:
		return true
	case N1504:
		return true
	case N1600:
		return true
	case N1601:
		return true
	case N1700:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationUserStatusType.
const (
	OrganizationUserStatusTypeN0 OrganizationUserStatusType = 0
	OrganizationUserStatusTypeN1 OrganizationUserStatusType = 1
	OrganizationUserStatusTypeN2 OrganizationUserStatusType = 2
)

// Valid indicates whether the value is a known member of the OrganizationUserStatusType enum.
func (e OrganizationUserStatusType) Valid() bool {
	switch e {
	case OrganizationUserStatusTypeN0:
		return true
	case OrganizationUserStatusTypeN1:
		return true
	case OrganizationUserStatusTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationUserType.
const (
	OrganizationUserTypeN0 OrganizationUserType = 0
	OrganizationUserTypeN1 OrganizationUserType = 1
	OrganizationUserTypeN2 OrganizationUserType = 2
	OrganizationUserTypeN3 OrganizationUserType = 3
)

// Valid indicates whether the value is a known member of the OrganizationUserType enum.
func (e OrganizationUserType) Valid() bool {
	switch e {
	case OrganizationUserTypeN0:
		return true
	case OrganizationUserTypeN1:
		return true
	case OrganizationUserTypeN2:
		return true
	case OrganizationUserTypeN3:
		return true
	default:
		return false
	}
}

// Defines values for PolicyType.
const (
	PolicyTypeN0 PolicyType = 0
	PolicyTypeN1 PolicyType = 1
	PolicyTypeN2 PolicyType = 2
)

// Valid indicates whether the value is a known member of the PolicyType enum.
func (e PolicyType) Valid() bool {
	switch e {
	case PolicyTypeN0:
		return true
	case PolicyTypeN1:
		return true
	case PolicyTypeN2:
		return true
	default:
		return false
	}
}

// AssociationWithPermissionsRequestModel defines model for AssociationWithPermissionsRequestModel.
type AssociationWithPermissionsRequestModel struct {
	// Id The associated object's unique identifier.
	//
	// Example: bfbc8338-e329-4dc0-b0c9-317c2ebf1a09
	Id openapi_types.UUID `json:"id"`

	// ReadOnly When true, the read only permission will not allow the user or group to make changes to items.
	ReadOnly bool `json:"readOnly"`
}

// AssociationWithPermissionsResponseModel defines model for AssociationWithPermissionsResponseModel.
type AssociationWithPermissionsResponseModel struct {
	// Id The associated object's unique identifier.
	//
	// Example: bfbc8338-e329-4dc0-b0c9-317c2ebf1a09
	Id openapi_types.UUID `json:"id"`

	// ReadOnly When true, the read only permission will not allow the user or group to make changes to items.
	ReadOnly bool `json:"readOnly"`
}

// CollectionResponseModel A collection.
type CollectionResponseModel struct {
	// ExternalId External identifier for reference or linking this collection to another system.
	//
	// Example: external_id_123456
	ExternalId *string `json:"externalId,omitempty"`

	// Groups The associated groups that this collection is assigned to.
	Groups *[]AssociationWithPermissionsResponseModel `json:"groups,omitempty"`

	// Id The collection's unique identifier.
	//
	// Example: 539a36c5-e0d2-4cf9-979e-51ecf5cf6593
	Id openapi_types.UUID `json:"id"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: collection
	Object *string `json:"object,omitempty"`
}

// CollectionResponseModelListResponseModel defines model for CollectionResponseModelListResponseModel.
type CollectionResponseModelListResponseModel struct {
	// ContinuationToken A cursor for use in pagination.
	ContinuationToken *string `json:"continuationToken,omitempty"`

	// Data An array containing the actual response elements, paginated by any request parameters.
	Data []CollectionResponseModel `json:"data"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: list
	Object *string `json:"object,omitempty"`
}

// CollectionUpdateRequestModel defines model for CollectionUpdateRequestModel.
type CollectionUpdateRequestModel struct {
	// ExternalId External identifier for reference or linking this collection to another system.
	//
	// Example: external_id_123456
	ExternalId *string `json:"externalId,omitempty"`

	// Groups The associated groups that this collection is assigned to.
	Groups *[]AssociationWithPermissionsRequestModel `json:"groups,omitempty"`
}

// DeviceType defines model for DeviceType.
type DeviceType int32

// ErrorResponseModel defines model for ErrorResponseModel.
type ErrorResponseModel struct {
	// Errors If multiple errors occurred, they are listed in dictionary. Errors related to a specific
	// request parameter will include a dictionary key describing that parameter.
	Errors *map[string][]string `json:"errors,omitempty"`

	// Message A human-readable message providing details about the error.
	//
	// Example: The request model is invalid.
	Message string `json:"message"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: error
	Object *string `json:"object,omitempty"`
}

// EventResponseModel An event log.
type EventResponseModel struct {
	// ActingUserId The unique identifier of the user that performed the event.
	//
	// Example: a2549f79-a71f-4eb9-9234-eb7247333f94
	ActingUserId *openapi_types.UUID `json:"actingUserId,omitempty"`

	// CollectionId The unique identifier of the related collection that the event describes.
	//
	// Example: bce212a4-25f3-4888-8a0a-4c5736d851e0
	CollectionId *openapi_types.UUID `json:"collectionId,omitempty"`

	// Date The date/timestamp when the event occurred.
	Date time.Time `json:"date"`

	// Device The type of device used by the acting user when the event occurred.
	Device *DeviceType `json:"device,omitempty"`

	// GroupId The unique identifier of the related group that the event describes.
	//
	// Example: f29a2515-91d2-4452-b49b-5e8040e6b0f4
	GroupId *openapi_types.UUID `json:"groupId,omitempty"`

	// IpAddress The IP address of the acting user.
	//
	// Example: 172.16.254.1
	IpAddress *string `json:"ipAddress,omitempty"`

	// ItemId The unique identifier of the related item that the event describes.
	//
	// Example: 3767a302-8208-4dc6-b842-030428a1cfad
	ItemId *openapi_types.UUID `json:"itemId,omitempty"`

	// MemberId The unique identifier of the related member that the event describes.
	//
	// Example: e68b8629-85eb-4929-92c0-b84464976ba4
	MemberId *openapi_types.UUID `json:"memberId,omitempty"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: event
	Object *string `json:"object,omitempty"`

	// PolicyId The unique identifier of the related policy that the event describes.
	//
	// Example: f29a2515-91d2-4452-b49b-5e8040e6b0f4
	PolicyId *openapi_types.UUID `json:"policyId,omitempty"`

	// Type The type of event.
	Type EventType `json:"type"`
}

// EventResponseModelListResponseModel defines model for EventResponseModelListResponseModel.
type EventResponseModelListResponseModel struct {
	// ContinuationToken A cursor for use in pagination.
	ContinuationToken *string `json:"continuationToken,omitempty"`

	// Data An array containing the actual response elements, paginated by any request parameters.
	Data []EventResponseModel `json:"data"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: list
	Object *string `json:"object,omitempty"`
}

// EventType defines model for EventType.
type EventType int32

// GroupCreateUpdateRequestModel defines model for GroupCreateUpdateRequestModel.
type GroupCreateUpdateRequestModel struct {
	// AccessAll Determines if this group can access all collections within the organization, or only the associated
	// collections. If set to {true}, this option overrides any collection assignments.
	AccessAll bool `json:"accessAll"`

	// Collections The associated collections that this group can access.
	Collections *[]AssociationWithPermissionsRequestModel `json:"collections,omitempty"`

	// ExternalId External identifier for reference or linking this group to another system, such as a user directory.
	//
	// Example: external_id_123456
	ExternalId *string `json:"externalId,omitempty"`

	// Name The name of the group.
	//
	// Example: Development Team
	Name string `json:"name"`
}

// GroupResponseModel A user group.
type GroupResponseModel struct {
	// AccessAll Determines if this group can access all collections within the organization, or only the associated
	// collections. If set to {true}, this option overrides any collection assignments.
	AccessAll bool `json:"accessAll"`

	// Collections The associated collections that this group can access.
	Collections *[]AssociationWithPermissionsResponseModel `json:"collections,omitempty"`

	// ExternalId External identifier for reference or linking this group to another system, such as a user directory.
	//
	// Example: external_id_123456
	ExternalId *string `json:"externalId,omitempty"`

	// Id The group's unique identifier.
	//
	// Example: 539a36c5-e0d2-4cf9-979e-51ecf5cf6593
	Id openapi_types.UUID `json:"id"`

	// Name The name of the group.
	//
	// Example: Development Team
	Name string `json:"name"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: group
	Object *string `json:"object,omitempty"`
}

// GroupResponseModelListResponseModel defines model for GroupResponseModelListResponseModel.
type GroupResponseModelListResponseModel struct {
	// ContinuationToken A cursor for use in pagination.
	ContinuationToken *string `json:"continuationToken,omitempty"`

	// Data An array containing the actual response elements, paginated by any request parameters.
	Data []GroupResponseModel `json:"data"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: list
	Object *string `json:"object,omitempty"`
}

// MemberCreateRequestModel defines model for MemberCreateRequestModel.
type MemberCreateRequestModel struct {
	// AccessAll Determines if this member can access all collections within the organization, or only the associated
	// collections. If set to {true}, this option overrides any collection assignments.
	AccessAll bool `json:"accessAll"`

	// Collections The associated collections that this member can access.
	Collections *[]AssociationWithPermissionsRequestModel `json:"collections,omitempty"`

	// Email The member's email address.
	//
	// Example: jsmith@example.com
	Email openapi_types.Email `json:"email"`

	// ExternalId External identifier for reference or linking this member to another system, such as a user directory.
	//
	// Example: external_id_123456
	ExternalId *string `json:"externalId,omitempty"`

	// Type The member's type (or role) within the organization.
	Type OrganizationUserType `json:"type"`
}

// MemberResponseModel An organization member.
type MemberResponseModel struct {
	// AccessAll Determines if this member can access all collections within the organization, or only the associated
	// collections. If set to {true}, this option overrides any collection assignments.
	AccessAll bool `json:"accessAll"`

	// Collections The associated collections that this member can access.
	Collections *[]AssociationWithPermissionsResponseModel `json:"collections,omitempty"`

	// Email The member's email address.
	//
	// Example: jsmith@example.com
	Email string `json:"email"`

	// ExternalId External identifier for reference or linking this member to another system, such as a user directory.
	//
	// Example: external_id_123456
	ExternalId *string `json:"externalId,omitempty"`

	// Id The member's unique identifier within the organization.
	//
	// Example: 539a36c5-e0d2-4cf9-979e-51ecf5cf6593
	Id openapi_types.UUID `json:"id"`

	// Name The member's name, set from their user account profile.
	//
	// Example: John Smith
	Name *string `json:"name,omitempty"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: member
	Object *string `json:"object,omitempty"`

	// Status The member's status within the organization. All created members start with a status of "Invited".
	// Once a member accept's their invitation to join the organization, their status changes to "Accepted".
	// Accepted members are then "Confirmed" by an organization administrator. Once a member is "Confirmed",
	// their status can no longer change.
	Status OrganizationUserStatusType `json:"status"`

	// TwoFactorEnabled Returns {true} if the member has a two-step login method enabled on their user account.
	TwoFactorEnabled bool `json:"twoFactorEnabled"`

	// Type The member's type (or role) within the organization.
	Type OrganizationUserType `json:"type"`

	// UserId The member's unique identifier across Bitwarden.
	//
	// Example: 48b47ee1-493e-4c67-aef7-014996c40eca
	UserId openapi_types.UUID `json:"userId"`
}

// MemberResponseModelListResponseModel defines model for MemberResponseModelListResponseModel.
type MemberResponseModelListResponseModel struct {
	// ContinuationToken A cursor for use in pagination.
	ContinuationToken *string `json:"continuationToken,omitempty"`

	// Data An array containing the actual response elements, paginated by any request parameters.
	Data []MemberResponseModel `json:"data"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: list
	Object *string `json:"object,omitempty"`
}

// MemberUpdateRequestModel defines model for MemberUpdateRequestModel.
type MemberUpdateRequestModel struct {
	// AccessAll Determines if this member can access all collections within the organization, or only the associated
	// collections. If set to {true}, this option overrides any collection assignments.
	AccessAll bool `json:"accessAll"`

	// Collections The associated collections that this member can access.
	Collections *[]AssociationWithPermissionsRequestModel `json:"collections,omitempty"`

	// ExternalId External identifier for reference or linking this member to another system, such as a user directory.
	//
	// Example: external_id_123456
	ExternalId *string `json:"externalId,omitempty"`

	// Type The member's type (or role) within the organization.
	Type OrganizationUserType `json:"type"`
}

// OrganizationImportGroupRequestModel defines model for OrganizationImportGroupRequestModel.
type OrganizationImportGroupRequestModel struct {
	// ExternalId External identifier for reference or linking this group to another system, such as a user directory.
	//
	// Example: external_id_123456
	ExternalId string `json:"externalId"`

	// MemberExternalIds The associated external ids for members in this group.
	MemberExternalIds *[]string `json:"memberExternalIds,omitempty"`

	// Name The name of the group.
	//
	// Example: Development Team
	Name string `json:"name"`
}

// OrganizationImportMemberRequestModel defines model for OrganizationImportMemberRequestModel.
type OrganizationImportMemberRequestModel struct {
	// Deleted Determines if this member should be removed from the organization during import.
	Deleted *bool `json:"deleted,omitempty"`

	// Email The member's email address. Required for non-deleted users.
	//
	// Example: jsmith@example.com
	Email *openapi_types.Email `json:"email,omitempty"`

	// ExternalId External identifier for reference or linking this member to another system, such as a user directory.
	//
	// Example: external_id_123456
	ExternalId string `json:"externalId"`
}

// OrganizationImportRequestModel defines model for OrganizationImportRequestModel.
type OrganizationImportRequestModel struct {
	// Groups Groups to import.
	Groups *[]OrganizationImportGroupRequestModel `json:"groups,omitempty"`

	// Members Members to import.
	Members *[]OrganizationImportMemberRequestModel `json:"members,omitempty"`

	// OverwriteExisting Determines if the data in this request should overwrite or append to the existing organization data.
	OverwriteExisting bool `json:"overwriteExisting"`
}

// OrganizationUserStatusType defines model for OrganizationUserStatusType.
type OrganizationUserStatusType int32

// OrganizationUserType defines model for OrganizationUserType.
type OrganizationUserType int32

// PolicyResponseModel A policy.
type PolicyResponseModel struct {
	// Data Data for the policy.
	Data *map[string]map[string]interface{} `json:"data,omitempty"`

	// Enabled Determines if this policy is enabled and enforced.
	Enabled bool `json:"enabled"`

	// Id The policy's unique identifier.
	//
	// Example: 539a36c5-e0d2-4cf9-979e-51ecf5cf6593
	Id openapi_types.UUID `json:"id"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: policy
	Object *string `json:"object,omitempty"`

	// Type The type of policy.
	Type PolicyType `json:"type"`
}

// PolicyResponseModelListResponseModel defines model for PolicyResponseModelListResponseModel.
type PolicyResponseModelListResponseModel struct {
	// ContinuationToken A cursor for use in pagination.
	ContinuationToken *string `json:"continuationToken,omitempty"`

	// Data An array containing the actual response elements, paginated by any request parameters.
	Data []PolicyResponseModel `json:"data"`

	// Object String representing the object's type. Objects of the same type share the same properties.
	//
	// Example: list
	Object *string `json:"object,omitempty"`
}

// PolicyType defines model for PolicyType.
type PolicyType int32

// PolicyUpdateRequestModel defines model for PolicyUpdateRequestModel.
type PolicyUpdateRequestModel struct {
	// Data Data for the policy.
	Data *map[string]map[string]interface{} `json:"data,omitempty"`

	// Enabled Determines if this policy is enabled and enforced.
	Enabled bool `json:"enabled"`
}

// UpdateGroupIdsRequestModel defines model for UpdateGroupIdsRequestModel.
type UpdateGroupIdsRequestModel struct {
	// GroupIds The associated group ids that this object can access.
	GroupIds *[]openapi_types.UUID `json:"groupIds,omitempty"`
}

// UpdateMemberIdsRequestModel defines model for UpdateMemberIdsRequestModel.
type UpdateMemberIdsRequestModel struct {
	// MemberIds The associated member ids that have access to this object.
	MemberIds *[]openapi_types.UUID `json:"memberIds,omitempty"`
}

// GetPublicEventsParams defines parameters for GetPublicEvents.
type GetPublicEventsParams struct {
	// Start The start date. Must be less than the end date.
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`

	// End The end date. Must be greater than the start date.
	End *time.Time `form:"end,omitempty" json:"end,omitempty"`

	// ActingUserId The unique identifier of the user that performed the event.
	ActingUserId *openapi_types.UUID `form:"actingUserId,omitempty" json:"actingUserId,omitempty"`

	// ItemId The unique identifier of the related item that the event describes.
	ItemId *openapi_types.UUID `form:"itemId,omitempty" json:"itemId,omitempty"`

	// ContinuationToken A cursor for use in pagination.
	ContinuationToken *string `form:"continuationToken,omitempty" json:"continuationToken,omitempty"`
}

// PutPublicPoliciesIdParams defines parameters for PutPublicPoliciesId.
type PutPublicPoliciesIdParams struct {
	// Type The type of policy to be updated.
	Type *PolicyType `form:"type,omitempty" json:"type,omitempty"`
}

// PutPublicCollectionsIdApplicationWildcardPlusJSONRequestBody defines body for PutPublicCollectionsId for application/*+json ContentType.
type PutPublicCollectionsIdApplicationWildcardPlusJSONRequestBody = CollectionUpdateRequestModel

// PutPublicCollectionsIdJSONRequestBody defines body for PutPublicCollectionsId for application/json ContentType.
type PutPublicCollectionsIdJSONRequestBody = CollectionUpdateRequestModel

// PutPublicCollectionsIdApplicationJSONPatchPlusJSONRequestBody defines body for PutPublicCollectionsId for application/json-patch+json ContentType.
type PutPublicCollectionsIdApplicationJSONPatchPlusJSONRequestBody = CollectionUpdateRequestModel

// PostPublicGroupsApplicationWildcardPlusJSONRequestBody defines body for PostPublicGroups for application/*+json ContentType.
type PostPublicGroupsApplicationWildcardPlusJSONRequestBody = GroupCreateUpdateRequestModel

// PostPublicGroupsJSONRequestBody defines body for PostPublicGroups for application/json ContentType.
type PostPublicGroupsJSONRequestBody = GroupCreateUpdateRequestModel

// PostPublicGroupsApplicationJSONPatchPlusJSONRequestBody defines body for PostPublicGroups for application/json-patch+json ContentType.
type PostPublicGroupsApplicationJSONPatchPlusJSONRequestBody = GroupCreateUpdateRequestModel

// PutPublicGroupsIdApplicationWildcardPlusJSONRequestBody defines body for PutPublicGroupsId for application/*+json ContentType.
type PutPublicGroupsIdApplicationWildcardPlusJSONRequestBody = GroupCreateUpdateRequestModel

// PutPublicGroupsIdJSONRequestBody defines body for PutPublicGroupsId for application/json ContentType.
type PutPublicGroupsIdJSONRequestBody = GroupCreateUpdateRequestModel

// PutPublicGroupsIdApplicationJSONPatchPlusJSONRequestBody defines body for PutPublicGroupsId for application/json-patch+json ContentType.
type PutPublicGroupsIdApplicationJSONPatchPlusJSONRequestBody = GroupCreateUpdateRequestModel

// PutPublicGroupsIdMemberIdsApplicationWildcardPlusJSONRequestBody defines body for PutPublicGroupsIdMemberIds for application/*+json ContentType.
type PutPublicGroupsIdMemberIdsApplicationWildcardPlusJSONRequestBody = UpdateMemberIdsRequestModel

// PutPublicGroupsIdMemberIdsJSONRequestBody defines body for PutPublicGroupsIdMemberIds for application/json ContentType.
type PutPublicGroupsIdMemberIdsJSONRequestBody = UpdateMemberIdsRequestModel

// PutPublicGroupsIdMemberIdsApplicationJSONPatchPlusJSONRequestBody defines body for PutPublicGroupsIdMemberIds for application/json-patch+json ContentType.
type PutPublicGroupsIdMemberIdsApplicationJSONPatchPlusJSONRequestBody = UpdateMemberIdsRequestModel

// PostPublicMembersApplicationWildcardPlusJSONRequestBody defines body for PostPublicMembers for application/*+json ContentType.
type PostPublicMembersApplicationWildcardPlusJSONRequestBody = MemberCreateRequestModel

// PostPublicMembersJSONRequestBody defines body for PostPublicMembers for application/json ContentType.
type PostPublicMembersJSONRequestBody = MemberCreateRequestModel

// PostPublicMembersApplicationJSONPatchPlusJSONRequestBody defines body for PostPublicMembers for application/json-patch+json ContentType.
type PostPublicMembersApplicationJSONPatchPlusJSONRequestBody = MemberCreateRequestModel

// PutPublicMembersIdApplicationWildcardPlusJSONRequestBody defines body for PutPublicMembersId for application/*+json ContentType.
type PutPublicMembersIdApplicationWildcardPlusJSONRequestBody = MemberUpdateRequestModel

// PutPublicMembersIdJSONRequestBody defines body for PutPublicMembersId for application/json ContentType.
type PutPublicMembersIdJSONRequestBody = MemberUpdateRequestModel

// PutPublicMembersIdApplicationJSONPatchPlusJSONRequestBody defines body for PutPublicMembersId for application/json-patch+json ContentType.
type PutPublicMembersIdApplicationJSONPatchPlusJSONRequestBody = MemberUpdateRequestModel

// PutPublicMembersIdGroupIdsApplicationWildcardPlusJSONRequestBody defines body for PutPublicMembersIdGroupIds for application/*+json ContentType.
type PutPublicMembersIdGroupIdsApplicationWildcardPlusJSONRequestBody = UpdateGroupIdsRequestModel

// PutPublicMembersIdGroupIdsJSONRequestBody defines body for PutPublicMembersIdGroupIds for application/json ContentType.
type PutPublicMembersIdGroupIdsJSONRequestBody = UpdateGroupIdsRequestModel

// PutPublicMembersIdGroupIdsApplicationJSONPatchPlusJSONRequestBody defines body for PutPublicMembersIdGroupIds for application/json-patch+json ContentType.
type PutPublicMembersIdGroupIdsApplicationJSONPatchPlusJSONRequestBody = UpdateGroupIdsRequestModel

// PostPublicOrganizationImportApplicationWildcardPlusJSONRequestBody defines body for PostPublicOrganizationImport for application/*+json ContentType.
type PostPublicOrganizationImportApplicationWildcardPlusJSONRequestBody = OrganizationImportRequestModel

// PostPublicOrganizationImportJSONRequestBody defines body for PostPublicOrganizationImport for application/json ContentType.
type PostPublicOrganizationImportJSONRequestBody = OrganizationImportRequestModel

// PostPublicOrganizationImportApplicationJSONPatchPlusJSONRequestBody defines body for PostPublicOrganizationImport for application/json-patch+json ContentType.
type PostPublicOrganizationImportApplicationJSONPatchPlusJSONRequestBody = OrganizationImportRequestModel

// PutPublicPoliciesIdApplicationWildcardPlusJSONRequestBody defines body for PutPublicPoliciesId for application/*+json ContentType.
type PutPublicPoliciesIdApplicationWildcardPlusJSONRequestBody = PolicyUpdateRequestModel

// PutPublicPoliciesIdJSONRequestBody defines body for PutPublicPoliciesId for application/json ContentType.
type PutPublicPoliciesIdJSONRequestBody = PolicyUpdateRequestModel

// PutPublicPoliciesIdApplicationJSONPatchPlusJSONRequestBody defines body for PutPublicPoliciesId for application/json-patch+json ContentType.
type PutPublicPoliciesIdApplicationJSONPatchPlusJSONRequestBody = PolicyUpdateRequestModel
