name: goreleaser edge containers

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      upload-artifacts:
        description: "Upload artifacts to workflow"
        required: false
        default: false
        type: boolean
      dry-run:
        description: "Skip publishing to registry (build only)"
        required: false
        default: false
        type: boolean

concurrency:
  group: goreleaser-edge
  cancel-in-progress: true

env:
  REGISTRY: docker.io

permissions:
  contents: read

jobs:
  goreleaser:
    permissions:
      # Add "contents" to write release
      contents: "write"
      # Add "id-token" for google-github-actions/auth
      id-token: "write"

    runs-on:
      group: arc-runners
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ">=${{ env.golang-version }}"
          check-latest: true
          cache: false

      - name: Install Protoc
        uses: ./.github/actions/setup-protoc
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.protoc-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Inspect builder
        run: docker buildx inspect --bootstrap

      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Locally tag the current commit
        run: |
          VERSION=$(make version)
          git tag ${VERSION/\+/-}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          # auto-update: source=github-releases repo=goreleaser/goreleaser updates=minor
          version: v2.17.0
          args: release -f .github/.goreleaser-edge.yml --clean --timeout 120m ${{ inputs.dry-run == true && '--skip=publish' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NFPM_DEFAULT_RPM_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts == true }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: mql-edge-linux
          path: dist/mql*
          retention-days: 7
