---
name: Lint Packs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate changed packs
    steps:
      - uses: actions/checkout@v4
      - name: Installing cnquery
        run: |
          bash -c "$(curl -sSL https://install.mondoo.com/sh/cnquery)"
      - name: Lint packs
        run: |
          cnquery bundle validate .
