name: Release Packs

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "**/*.mql.yaml"
          generate_release_notes: true
          fail_on_unmatched_files: true
      - name: Trigger Registry Update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SERVER_ACTION_TOKEN }}
          repository: mondoohq/server
          event-type: update
          client-payload: '{"source": "${{ github.repository }}", "tag": "${{ github.ref }}"}'
