name: Spell Check
permissions:
  contents: read
on: [pull_request]
jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@v1.46.0
