name: Test .github/scripts

on:
  pull_request:
    paths:
      - '.github/scripts/**'
      - '.github/workflows/test-scripts.yml'
  push:
    branches: [main, v13]
    paths:
      - '.github/scripts/**'
      - '.github/workflows/test-scripts.yml'

permissions:
  contents: read

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run bats tests
        run: bats -r .github/scripts/tests
