name: Update pinned versions

on:
  schedule:
    - cron: "22 8 * * 1" # every monday
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-versions:
    uses: mondoohq/actions/.github/workflows/update-pinned-versions.yml@b41754752763419780430abef5e35842ba2bec66 # main
    permissions:
      contents: write
      pull-requests: write
    secrets:
      ssh-key: ${{ secrets.CNQUERY_DEPLOY_KEY_PRIV }}
