name: Update pinned versions

on:
  schedule:
    - cron: "22 8 * * 1" # every monday
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-versions:
    uses: mondoohq/actions/.github/workflows/update-pinned-versions.yml@c09ff90232c442d736990f184a438a844bec4cb1 # main
    permissions:
      contents: write
      pull-requests: write
    secrets:
      ssh-key: ${{ secrets.CNQUERY_DEPLOY_KEY_PRIV }}
